package org.hf.jsem.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.hf.jsem.entity.AmMenu;
import org.hf.jsem.entity.AmMenuExample;

public interface AmMenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table am_menu
     *
     * @mbggenerated Mon Oct 31 21:34:23 CST 2016
     */
    int countByExample(AmMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table am_menu
     *
     * @mbggenerated Mon Oct 31 21:34:23 CST 2016
     */
    int deleteByExample(AmMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table am_menu
     *
     * @mbggenerated Mon Oct 31 21:34:23 CST 2016
     */
    int deleteByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table am_menu
     *
     * @mbggenerated Mon Oct 31 21:34:23 CST 2016
     */
    int insert(AmMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table am_menu
     *
     * @mbggenerated Mon Oct 31 21:34:23 CST 2016
     */
    int insertSelective(AmMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table am_menu
     *
     * @mbggenerated Mon Oct 31 21:34:23 CST 2016
     */
    List<AmMenu> selectByExampleWithBLOBs(AmMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table am_menu
     *
     * @mbggenerated Mon Oct 31 21:34:23 CST 2016
     */
    List<AmMenu> selectByExample(AmMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table am_menu
     *
     * @mbggenerated Mon Oct 31 21:34:23 CST 2016
     */
    AmMenu selectByPrimaryKey(Integer menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table am_menu
     *
     * @mbggenerated Mon Oct 31 21:34:23 CST 2016
     */
    int updateByExampleSelective(@Param("record") AmMenu record, @Param("example") AmMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table am_menu
     *
     * @mbggenerated Mon Oct 31 21:34:23 CST 2016
     */
    int updateByExampleWithBLOBs(@Param("record") AmMenu record, @Param("example") AmMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table am_menu
     *
     * @mbggenerated Mon Oct 31 21:34:23 CST 2016
     */
    int updateByExample(@Param("record") AmMenu record, @Param("example") AmMenuExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table am_menu
     *
     * @mbggenerated Mon Oct 31 21:34:23 CST 2016
     */
    int updateByPrimaryKeySelective(AmMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table am_menu
     *
     * @mbggenerated Mon Oct 31 21:34:23 CST 2016
     */
    int updateByPrimaryKeyWithBLOBs(AmMenu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table am_menu
     *
     * @mbggenerated Mon Oct 31 21:34:23 CST 2016
     */
    int updateByPrimaryKey(AmMenu record);
}