package org.hf.jsem.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.hf.jsem.entity.JcmProcess;
import org.hf.jsem.entity.JcmProcessExample;

public interface JcmProcessMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    int countByExample(JcmProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    int deleteByExample(JcmProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    int deleteByPrimaryKey(String workType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    int insert(JcmProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    int insertSelective(JcmProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    List<JcmProcess> selectByExample(JcmProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    JcmProcess selectByPrimaryKey(String workType);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    int updateByExampleSelective(@Param("record") JcmProcess record, @Param("example") JcmProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    int updateByExample(@Param("record") JcmProcess record, @Param("example") JcmProcessExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    int updateByPrimaryKeySelective(JcmProcess record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    int updateByPrimaryKey(JcmProcess record);
}