package org.hf.jsem.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.hf.jsem.entity.SscfChannel;
import org.hf.jsem.entity.SscfChannelExample;

public interface SscfChannelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_CHANNEL
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    int countByExample(SscfChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_CHANNEL
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    int deleteByExample(SscfChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_CHANNEL
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    int deleteByPrimaryKey(String channelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_CHANNEL
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    int insert(SscfChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_CHANNEL
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    int insertSelective(SscfChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_CHANNEL
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    List<SscfChannel> selectByExample(SscfChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_CHANNEL
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    SscfChannel selectByPrimaryKey(String channelId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_CHANNEL
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    int updateByExampleSelective(@Param("record") SscfChannel record, @Param("example") SscfChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_CHANNEL
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    int updateByExample(@Param("record") SscfChannel record, @Param("example") SscfChannelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_CHANNEL
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    int updateByPrimaryKeySelective(SscfChannel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_CHANNEL
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    int updateByPrimaryKey(SscfChannel record);
}