package org.hf.jsem.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Options;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.mapping.StatementType;
import org.hf.jsem.entity.SscfLnmtCaafverDtl;
import org.hf.jsem.entity.SscfLnmtCaafverDtlExample;

public interface SscfLnmtCaafverDtlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_LNMT_CAAFVER_DTL
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    int countByExample(SscfLnmtCaafverDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_LNMT_CAAFVER_DTL
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    int deleteByExample(SscfLnmtCaafverDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_LNMT_CAAFVER_DTL
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    int insert(SscfLnmtCaafverDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_LNMT_CAAFVER_DTL
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    int insertSelective(SscfLnmtCaafverDtl record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_LNMT_CAAFVER_DTL
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    List<SscfLnmtCaafverDtl> selectByExample(SscfLnmtCaafverDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_LNMT_CAAFVER_DTL
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    int updateByExampleSelective(@Param("record") SscfLnmtCaafverDtl record, @Param("example") SscfLnmtCaafverDtlExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_LNMT_CAAFVER_DTL
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    int updateByExample(@Param("record") SscfLnmtCaafverDtl record, @Param("example") SscfLnmtCaafverDtlExample example);


    void doHxActCprSucc(Map<String, Object> params);

    void doHxActCprFail(Map<String, Object> params);
}