package org.hf.jsem.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.hf.jsem.entity.SscfWorkMain;
import org.hf.jsem.entity.SscfWorkMainExample;

public interface SscfWorkMainMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    int countByExample(SscfWorkMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    int deleteByExample(SscfWorkMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    int insert(SscfWorkMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    int insertSelective(SscfWorkMain record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    List<SscfWorkMain> selectByExample(SscfWorkMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    int updateByExampleSelective(@Param("record") SscfWorkMain record, @Param("example") SscfWorkMainExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    int updateByExample(@Param("record") SscfWorkMain record, @Param("example") SscfWorkMainExample example);
}