package org.hf.jsem.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JcmJobInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated Tue Nov 29 14:18:05 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated Tue Nov 29 14:18:05 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated Tue Nov 29 14:18:05 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated Tue Nov 29 14:18:05 CST 2016
     */
    public JcmJobInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated Tue Nov 29 14:18:05 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated Tue Nov 29 14:18:05 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated Tue Nov 29 14:18:05 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated Tue Nov 29 14:18:05 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated Tue Nov 29 14:18:05 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated Tue Nov 29 14:18:05 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated Tue Nov 29 14:18:05 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated Tue Nov 29 14:18:05 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated Tue Nov 29 14:18:05 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated Tue Nov 29 14:18:05 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated Tue Nov 29 14:18:05 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andJobCdIsNull() {
            addCriterion("JOB_CD is null");
            return (Criteria) this;
        }

        public Criteria andJobCdIsNotNull() {
            addCriterion("JOB_CD is not null");
            return (Criteria) this;
        }

        public Criteria andJobCdEqualTo(String value) {
            addCriterion("JOB_CD =", value, "jobCd");
            return (Criteria) this;
        }

        public Criteria andJobCdNotEqualTo(String value) {
            addCriterion("JOB_CD <>", value, "jobCd");
            return (Criteria) this;
        }

        public Criteria andJobCdGreaterThan(String value) {
            addCriterion("JOB_CD >", value, "jobCd");
            return (Criteria) this;
        }

        public Criteria andJobCdGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_CD >=", value, "jobCd");
            return (Criteria) this;
        }

        public Criteria andJobCdLessThan(String value) {
            addCriterion("JOB_CD <", value, "jobCd");
            return (Criteria) this;
        }

        public Criteria andJobCdLessThanOrEqualTo(String value) {
            addCriterion("JOB_CD <=", value, "jobCd");
            return (Criteria) this;
        }

        public Criteria andJobCdLike(String value) {
            addCriterion("JOB_CD like", value, "jobCd");
            return (Criteria) this;
        }

        public Criteria andJobCdNotLike(String value) {
            addCriterion("JOB_CD not like", value, "jobCd");
            return (Criteria) this;
        }

        public Criteria andJobCdIn(List<String> values) {
            addCriterion("JOB_CD in", values, "jobCd");
            return (Criteria) this;
        }

        public Criteria andJobCdNotIn(List<String> values) {
            addCriterion("JOB_CD not in", values, "jobCd");
            return (Criteria) this;
        }

        public Criteria andJobCdBetween(String value1, String value2) {
            addCriterion("JOB_CD between", value1, value2, "jobCd");
            return (Criteria) this;
        }

        public Criteria andJobCdNotBetween(String value1, String value2) {
            addCriterion("JOB_CD not between", value1, value2, "jobCd");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIsNull() {
            addCriterion("WORK_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIsNotNull() {
            addCriterion("WORK_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andWorkTypeEqualTo(String value) {
            addCriterion("WORK_TYPE =", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotEqualTo(String value) {
            addCriterion("WORK_TYPE <>", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeGreaterThan(String value) {
            addCriterion("WORK_TYPE >", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeGreaterThanOrEqualTo(String value) {
            addCriterion("WORK_TYPE >=", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLessThan(String value) {
            addCriterion("WORK_TYPE <", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLessThanOrEqualTo(String value) {
            addCriterion("WORK_TYPE <=", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLike(String value) {
            addCriterion("WORK_TYPE like", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotLike(String value) {
            addCriterion("WORK_TYPE not like", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIn(List<String> values) {
            addCriterion("WORK_TYPE in", values, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotIn(List<String> values) {
            addCriterion("WORK_TYPE not in", values, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeBetween(String value1, String value2) {
            addCriterion("WORK_TYPE between", value1, value2, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotBetween(String value1, String value2) {
            addCriterion("WORK_TYPE not between", value1, value2, "workType");
            return (Criteria) this;
        }

        public Criteria andDataDateIsNull() {
            addCriterion("DATA_DATE is null");
            return (Criteria) this;
        }

        public Criteria andDataDateIsNotNull() {
            addCriterion("DATA_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andDataDateEqualTo(String value) {
            addCriterion("DATA_DATE =", value, "dataDate");
            return (Criteria) this;
        }

        public Criteria andDataDateNotEqualTo(String value) {
            addCriterion("DATA_DATE <>", value, "dataDate");
            return (Criteria) this;
        }

        public Criteria andDataDateGreaterThan(String value) {
            addCriterion("DATA_DATE >", value, "dataDate");
            return (Criteria) this;
        }

        public Criteria andDataDateGreaterThanOrEqualTo(String value) {
            addCriterion("DATA_DATE >=", value, "dataDate");
            return (Criteria) this;
        }

        public Criteria andDataDateLessThan(String value) {
            addCriterion("DATA_DATE <", value, "dataDate");
            return (Criteria) this;
        }

        public Criteria andDataDateLessThanOrEqualTo(String value) {
            addCriterion("DATA_DATE <=", value, "dataDate");
            return (Criteria) this;
        }

        public Criteria andDataDateLike(String value) {
            addCriterion("DATA_DATE like", value, "dataDate");
            return (Criteria) this;
        }

        public Criteria andDataDateNotLike(String value) {
            addCriterion("DATA_DATE not like", value, "dataDate");
            return (Criteria) this;
        }

        public Criteria andDataDateIn(List<String> values) {
            addCriterion("DATA_DATE in", values, "dataDate");
            return (Criteria) this;
        }

        public Criteria andDataDateNotIn(List<String> values) {
            addCriterion("DATA_DATE not in", values, "dataDate");
            return (Criteria) this;
        }

        public Criteria andDataDateBetween(String value1, String value2) {
            addCriterion("DATA_DATE between", value1, value2, "dataDate");
            return (Criteria) this;
        }

        public Criteria andDataDateNotBetween(String value1, String value2) {
            addCriterion("DATA_DATE not between", value1, value2, "dataDate");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNull() {
            addCriterion("JOB_NAME is null");
            return (Criteria) this;
        }

        public Criteria andJobNameIsNotNull() {
            addCriterion("JOB_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andJobNameEqualTo(String value) {
            addCriterion("JOB_NAME =", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotEqualTo(String value) {
            addCriterion("JOB_NAME <>", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThan(String value) {
            addCriterion("JOB_NAME >", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameGreaterThanOrEqualTo(String value) {
            addCriterion("JOB_NAME >=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThan(String value) {
            addCriterion("JOB_NAME <", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLessThanOrEqualTo(String value) {
            addCriterion("JOB_NAME <=", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameLike(String value) {
            addCriterion("JOB_NAME like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotLike(String value) {
            addCriterion("JOB_NAME not like", value, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameIn(List<String> values) {
            addCriterion("JOB_NAME in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotIn(List<String> values) {
            addCriterion("JOB_NAME not in", values, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameBetween(String value1, String value2) {
            addCriterion("JOB_NAME between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andJobNameNotBetween(String value1, String value2) {
            addCriterion("JOB_NAME not between", value1, value2, "jobName");
            return (Criteria) this;
        }

        public Criteria andFtpAdrIsNull() {
            addCriterion("FTP_ADR is null");
            return (Criteria) this;
        }

        public Criteria andFtpAdrIsNotNull() {
            addCriterion("FTP_ADR is not null");
            return (Criteria) this;
        }

        public Criteria andFtpAdrEqualTo(String value) {
            addCriterion("FTP_ADR =", value, "ftpAdr");
            return (Criteria) this;
        }

        public Criteria andFtpAdrNotEqualTo(String value) {
            addCriterion("FTP_ADR <>", value, "ftpAdr");
            return (Criteria) this;
        }

        public Criteria andFtpAdrGreaterThan(String value) {
            addCriterion("FTP_ADR >", value, "ftpAdr");
            return (Criteria) this;
        }

        public Criteria andFtpAdrGreaterThanOrEqualTo(String value) {
            addCriterion("FTP_ADR >=", value, "ftpAdr");
            return (Criteria) this;
        }

        public Criteria andFtpAdrLessThan(String value) {
            addCriterion("FTP_ADR <", value, "ftpAdr");
            return (Criteria) this;
        }

        public Criteria andFtpAdrLessThanOrEqualTo(String value) {
            addCriterion("FTP_ADR <=", value, "ftpAdr");
            return (Criteria) this;
        }

        public Criteria andFtpAdrLike(String value) {
            addCriterion("FTP_ADR like", value, "ftpAdr");
            return (Criteria) this;
        }

        public Criteria andFtpAdrNotLike(String value) {
            addCriterion("FTP_ADR not like", value, "ftpAdr");
            return (Criteria) this;
        }

        public Criteria andFtpAdrIn(List<String> values) {
            addCriterion("FTP_ADR in", values, "ftpAdr");
            return (Criteria) this;
        }

        public Criteria andFtpAdrNotIn(List<String> values) {
            addCriterion("FTP_ADR not in", values, "ftpAdr");
            return (Criteria) this;
        }

        public Criteria andFtpAdrBetween(String value1, String value2) {
            addCriterion("FTP_ADR between", value1, value2, "ftpAdr");
            return (Criteria) this;
        }

        public Criteria andFtpAdrNotBetween(String value1, String value2) {
            addCriterion("FTP_ADR not between", value1, value2, "ftpAdr");
            return (Criteria) this;
        }

        public Criteria andFtpUserIsNull() {
            addCriterion("FTP_USER is null");
            return (Criteria) this;
        }

        public Criteria andFtpUserIsNotNull() {
            addCriterion("FTP_USER is not null");
            return (Criteria) this;
        }

        public Criteria andFtpUserEqualTo(String value) {
            addCriterion("FTP_USER =", value, "ftpUser");
            return (Criteria) this;
        }

        public Criteria andFtpUserNotEqualTo(String value) {
            addCriterion("FTP_USER <>", value, "ftpUser");
            return (Criteria) this;
        }

        public Criteria andFtpUserGreaterThan(String value) {
            addCriterion("FTP_USER >", value, "ftpUser");
            return (Criteria) this;
        }

        public Criteria andFtpUserGreaterThanOrEqualTo(String value) {
            addCriterion("FTP_USER >=", value, "ftpUser");
            return (Criteria) this;
        }

        public Criteria andFtpUserLessThan(String value) {
            addCriterion("FTP_USER <", value, "ftpUser");
            return (Criteria) this;
        }

        public Criteria andFtpUserLessThanOrEqualTo(String value) {
            addCriterion("FTP_USER <=", value, "ftpUser");
            return (Criteria) this;
        }

        public Criteria andFtpUserLike(String value) {
            addCriterion("FTP_USER like", value, "ftpUser");
            return (Criteria) this;
        }

        public Criteria andFtpUserNotLike(String value) {
            addCriterion("FTP_USER not like", value, "ftpUser");
            return (Criteria) this;
        }

        public Criteria andFtpUserIn(List<String> values) {
            addCriterion("FTP_USER in", values, "ftpUser");
            return (Criteria) this;
        }

        public Criteria andFtpUserNotIn(List<String> values) {
            addCriterion("FTP_USER not in", values, "ftpUser");
            return (Criteria) this;
        }

        public Criteria andFtpUserBetween(String value1, String value2) {
            addCriterion("FTP_USER between", value1, value2, "ftpUser");
            return (Criteria) this;
        }

        public Criteria andFtpUserNotBetween(String value1, String value2) {
            addCriterion("FTP_USER not between", value1, value2, "ftpUser");
            return (Criteria) this;
        }

        public Criteria andFtpPwdIsNull() {
            addCriterion("FTP_PWD is null");
            return (Criteria) this;
        }

        public Criteria andFtpPwdIsNotNull() {
            addCriterion("FTP_PWD is not null");
            return (Criteria) this;
        }

        public Criteria andFtpPwdEqualTo(String value) {
            addCriterion("FTP_PWD =", value, "ftpPwd");
            return (Criteria) this;
        }

        public Criteria andFtpPwdNotEqualTo(String value) {
            addCriterion("FTP_PWD <>", value, "ftpPwd");
            return (Criteria) this;
        }

        public Criteria andFtpPwdGreaterThan(String value) {
            addCriterion("FTP_PWD >", value, "ftpPwd");
            return (Criteria) this;
        }

        public Criteria andFtpPwdGreaterThanOrEqualTo(String value) {
            addCriterion("FTP_PWD >=", value, "ftpPwd");
            return (Criteria) this;
        }

        public Criteria andFtpPwdLessThan(String value) {
            addCriterion("FTP_PWD <", value, "ftpPwd");
            return (Criteria) this;
        }

        public Criteria andFtpPwdLessThanOrEqualTo(String value) {
            addCriterion("FTP_PWD <=", value, "ftpPwd");
            return (Criteria) this;
        }

        public Criteria andFtpPwdLike(String value) {
            addCriterion("FTP_PWD like", value, "ftpPwd");
            return (Criteria) this;
        }

        public Criteria andFtpPwdNotLike(String value) {
            addCriterion("FTP_PWD not like", value, "ftpPwd");
            return (Criteria) this;
        }

        public Criteria andFtpPwdIn(List<String> values) {
            addCriterion("FTP_PWD in", values, "ftpPwd");
            return (Criteria) this;
        }

        public Criteria andFtpPwdNotIn(List<String> values) {
            addCriterion("FTP_PWD not in", values, "ftpPwd");
            return (Criteria) this;
        }

        public Criteria andFtpPwdBetween(String value1, String value2) {
            addCriterion("FTP_PWD between", value1, value2, "ftpPwd");
            return (Criteria) this;
        }

        public Criteria andFtpPwdNotBetween(String value1, String value2) {
            addCriterion("FTP_PWD not between", value1, value2, "ftpPwd");
            return (Criteria) this;
        }

        public Criteria andLocalDirIsNull() {
            addCriterion("LOCAL_DIR is null");
            return (Criteria) this;
        }

        public Criteria andLocalDirIsNotNull() {
            addCriterion("LOCAL_DIR is not null");
            return (Criteria) this;
        }

        public Criteria andLocalDirEqualTo(String value) {
            addCriterion("LOCAL_DIR =", value, "localDir");
            return (Criteria) this;
        }

        public Criteria andLocalDirNotEqualTo(String value) {
            addCriterion("LOCAL_DIR <>", value, "localDir");
            return (Criteria) this;
        }

        public Criteria andLocalDirGreaterThan(String value) {
            addCriterion("LOCAL_DIR >", value, "localDir");
            return (Criteria) this;
        }

        public Criteria andLocalDirGreaterThanOrEqualTo(String value) {
            addCriterion("LOCAL_DIR >=", value, "localDir");
            return (Criteria) this;
        }

        public Criteria andLocalDirLessThan(String value) {
            addCriterion("LOCAL_DIR <", value, "localDir");
            return (Criteria) this;
        }

        public Criteria andLocalDirLessThanOrEqualTo(String value) {
            addCriterion("LOCAL_DIR <=", value, "localDir");
            return (Criteria) this;
        }

        public Criteria andLocalDirLike(String value) {
            addCriterion("LOCAL_DIR like", value, "localDir");
            return (Criteria) this;
        }

        public Criteria andLocalDirNotLike(String value) {
            addCriterion("LOCAL_DIR not like", value, "localDir");
            return (Criteria) this;
        }

        public Criteria andLocalDirIn(List<String> values) {
            addCriterion("LOCAL_DIR in", values, "localDir");
            return (Criteria) this;
        }

        public Criteria andLocalDirNotIn(List<String> values) {
            addCriterion("LOCAL_DIR not in", values, "localDir");
            return (Criteria) this;
        }

        public Criteria andLocalDirBetween(String value1, String value2) {
            addCriterion("LOCAL_DIR between", value1, value2, "localDir");
            return (Criteria) this;
        }

        public Criteria andLocalDirNotBetween(String value1, String value2) {
            addCriterion("LOCAL_DIR not between", value1, value2, "localDir");
            return (Criteria) this;
        }

        public Criteria andDistanDirIsNull() {
            addCriterion("DISTAN_DIR is null");
            return (Criteria) this;
        }

        public Criteria andDistanDirIsNotNull() {
            addCriterion("DISTAN_DIR is not null");
            return (Criteria) this;
        }

        public Criteria andDistanDirEqualTo(String value) {
            addCriterion("DISTAN_DIR =", value, "distanDir");
            return (Criteria) this;
        }

        public Criteria andDistanDirNotEqualTo(String value) {
            addCriterion("DISTAN_DIR <>", value, "distanDir");
            return (Criteria) this;
        }

        public Criteria andDistanDirGreaterThan(String value) {
            addCriterion("DISTAN_DIR >", value, "distanDir");
            return (Criteria) this;
        }

        public Criteria andDistanDirGreaterThanOrEqualTo(String value) {
            addCriterion("DISTAN_DIR >=", value, "distanDir");
            return (Criteria) this;
        }

        public Criteria andDistanDirLessThan(String value) {
            addCriterion("DISTAN_DIR <", value, "distanDir");
            return (Criteria) this;
        }

        public Criteria andDistanDirLessThanOrEqualTo(String value) {
            addCriterion("DISTAN_DIR <=", value, "distanDir");
            return (Criteria) this;
        }

        public Criteria andDistanDirLike(String value) {
            addCriterion("DISTAN_DIR like", value, "distanDir");
            return (Criteria) this;
        }

        public Criteria andDistanDirNotLike(String value) {
            addCriterion("DISTAN_DIR not like", value, "distanDir");
            return (Criteria) this;
        }

        public Criteria andDistanDirIn(List<String> values) {
            addCriterion("DISTAN_DIR in", values, "distanDir");
            return (Criteria) this;
        }

        public Criteria andDistanDirNotIn(List<String> values) {
            addCriterion("DISTAN_DIR not in", values, "distanDir");
            return (Criteria) this;
        }

        public Criteria andDistanDirBetween(String value1, String value2) {
            addCriterion("DISTAN_DIR between", value1, value2, "distanDir");
            return (Criteria) this;
        }

        public Criteria andDistanDirNotBetween(String value1, String value2) {
            addCriterion("DISTAN_DIR not between", value1, value2, "distanDir");
            return (Criteria) this;
        }

        public Criteria andOkFileNameIsNull() {
            addCriterion("OK_FILE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andOkFileNameIsNotNull() {
            addCriterion("OK_FILE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andOkFileNameEqualTo(String value) {
            addCriterion("OK_FILE_NAME =", value, "okFileName");
            return (Criteria) this;
        }

        public Criteria andOkFileNameNotEqualTo(String value) {
            addCriterion("OK_FILE_NAME <>", value, "okFileName");
            return (Criteria) this;
        }

        public Criteria andOkFileNameGreaterThan(String value) {
            addCriterion("OK_FILE_NAME >", value, "okFileName");
            return (Criteria) this;
        }

        public Criteria andOkFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("OK_FILE_NAME >=", value, "okFileName");
            return (Criteria) this;
        }

        public Criteria andOkFileNameLessThan(String value) {
            addCriterion("OK_FILE_NAME <", value, "okFileName");
            return (Criteria) this;
        }

        public Criteria andOkFileNameLessThanOrEqualTo(String value) {
            addCriterion("OK_FILE_NAME <=", value, "okFileName");
            return (Criteria) this;
        }

        public Criteria andOkFileNameLike(String value) {
            addCriterion("OK_FILE_NAME like", value, "okFileName");
            return (Criteria) this;
        }

        public Criteria andOkFileNameNotLike(String value) {
            addCriterion("OK_FILE_NAME not like", value, "okFileName");
            return (Criteria) this;
        }

        public Criteria andOkFileNameIn(List<String> values) {
            addCriterion("OK_FILE_NAME in", values, "okFileName");
            return (Criteria) this;
        }

        public Criteria andOkFileNameNotIn(List<String> values) {
            addCriterion("OK_FILE_NAME not in", values, "okFileName");
            return (Criteria) this;
        }

        public Criteria andOkFileNameBetween(String value1, String value2) {
            addCriterion("OK_FILE_NAME between", value1, value2, "okFileName");
            return (Criteria) this;
        }

        public Criteria andOkFileNameNotBetween(String value1, String value2) {
            addCriterion("OK_FILE_NAME not between", value1, value2, "okFileName");
            return (Criteria) this;
        }

        public Criteria andConentFileNameIsNull() {
            addCriterion("CONENT_FILE_NAME is null");
            return (Criteria) this;
        }

        public Criteria andConentFileNameIsNotNull() {
            addCriterion("CONENT_FILE_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andConentFileNameEqualTo(String value) {
            addCriterion("CONENT_FILE_NAME =", value, "conentFileName");
            return (Criteria) this;
        }

        public Criteria andConentFileNameNotEqualTo(String value) {
            addCriterion("CONENT_FILE_NAME <>", value, "conentFileName");
            return (Criteria) this;
        }

        public Criteria andConentFileNameGreaterThan(String value) {
            addCriterion("CONENT_FILE_NAME >", value, "conentFileName");
            return (Criteria) this;
        }

        public Criteria andConentFileNameGreaterThanOrEqualTo(String value) {
            addCriterion("CONENT_FILE_NAME >=", value, "conentFileName");
            return (Criteria) this;
        }

        public Criteria andConentFileNameLessThan(String value) {
            addCriterion("CONENT_FILE_NAME <", value, "conentFileName");
            return (Criteria) this;
        }

        public Criteria andConentFileNameLessThanOrEqualTo(String value) {
            addCriterion("CONENT_FILE_NAME <=", value, "conentFileName");
            return (Criteria) this;
        }

        public Criteria andConentFileNameLike(String value) {
            addCriterion("CONENT_FILE_NAME like", value, "conentFileName");
            return (Criteria) this;
        }

        public Criteria andConentFileNameNotLike(String value) {
            addCriterion("CONENT_FILE_NAME not like", value, "conentFileName");
            return (Criteria) this;
        }

        public Criteria andConentFileNameIn(List<String> values) {
            addCriterion("CONENT_FILE_NAME in", values, "conentFileName");
            return (Criteria) this;
        }

        public Criteria andConentFileNameNotIn(List<String> values) {
            addCriterion("CONENT_FILE_NAME not in", values, "conentFileName");
            return (Criteria) this;
        }

        public Criteria andConentFileNameBetween(String value1, String value2) {
            addCriterion("CONENT_FILE_NAME between", value1, value2, "conentFileName");
            return (Criteria) this;
        }

        public Criteria andConentFileNameNotBetween(String value1, String value2) {
            addCriterion("CONENT_FILE_NAME not between", value1, value2, "conentFileName");
            return (Criteria) this;
        }

        public Criteria andSufffixIsNull() {
            addCriterion("SUFFFIX is null");
            return (Criteria) this;
        }

        public Criteria andSufffixIsNotNull() {
            addCriterion("SUFFFIX is not null");
            return (Criteria) this;
        }

        public Criteria andSufffixEqualTo(String value) {
            addCriterion("SUFFFIX =", value, "sufffix");
            return (Criteria) this;
        }

        public Criteria andSufffixNotEqualTo(String value) {
            addCriterion("SUFFFIX <>", value, "sufffix");
            return (Criteria) this;
        }

        public Criteria andSufffixGreaterThan(String value) {
            addCriterion("SUFFFIX >", value, "sufffix");
            return (Criteria) this;
        }

        public Criteria andSufffixGreaterThanOrEqualTo(String value) {
            addCriterion("SUFFFIX >=", value, "sufffix");
            return (Criteria) this;
        }

        public Criteria andSufffixLessThan(String value) {
            addCriterion("SUFFFIX <", value, "sufffix");
            return (Criteria) this;
        }

        public Criteria andSufffixLessThanOrEqualTo(String value) {
            addCriterion("SUFFFIX <=", value, "sufffix");
            return (Criteria) this;
        }

        public Criteria andSufffixLike(String value) {
            addCriterion("SUFFFIX like", value, "sufffix");
            return (Criteria) this;
        }

        public Criteria andSufffixNotLike(String value) {
            addCriterion("SUFFFIX not like", value, "sufffix");
            return (Criteria) this;
        }

        public Criteria andSufffixIn(List<String> values) {
            addCriterion("SUFFFIX in", values, "sufffix");
            return (Criteria) this;
        }

        public Criteria andSufffixNotIn(List<String> values) {
            addCriterion("SUFFFIX not in", values, "sufffix");
            return (Criteria) this;
        }

        public Criteria andSufffixBetween(String value1, String value2) {
            addCriterion("SUFFFIX between", value1, value2, "sufffix");
            return (Criteria) this;
        }

        public Criteria andSufffixNotBetween(String value1, String value2) {
            addCriterion("SUFFFIX not between", value1, value2, "sufffix");
            return (Criteria) this;
        }

        public Criteria andSuffixTimeFormatIsNull() {
            addCriterion("SUFFIX_TIME_FORMAT is null");
            return (Criteria) this;
        }

        public Criteria andSuffixTimeFormatIsNotNull() {
            addCriterion("SUFFIX_TIME_FORMAT is not null");
            return (Criteria) this;
        }

        public Criteria andSuffixTimeFormatEqualTo(String value) {
            addCriterion("SUFFIX_TIME_FORMAT =", value, "suffixTimeFormat");
            return (Criteria) this;
        }

        public Criteria andSuffixTimeFormatNotEqualTo(String value) {
            addCriterion("SUFFIX_TIME_FORMAT <>", value, "suffixTimeFormat");
            return (Criteria) this;
        }

        public Criteria andSuffixTimeFormatGreaterThan(String value) {
            addCriterion("SUFFIX_TIME_FORMAT >", value, "suffixTimeFormat");
            return (Criteria) this;
        }

        public Criteria andSuffixTimeFormatGreaterThanOrEqualTo(String value) {
            addCriterion("SUFFIX_TIME_FORMAT >=", value, "suffixTimeFormat");
            return (Criteria) this;
        }

        public Criteria andSuffixTimeFormatLessThan(String value) {
            addCriterion("SUFFIX_TIME_FORMAT <", value, "suffixTimeFormat");
            return (Criteria) this;
        }

        public Criteria andSuffixTimeFormatLessThanOrEqualTo(String value) {
            addCriterion("SUFFIX_TIME_FORMAT <=", value, "suffixTimeFormat");
            return (Criteria) this;
        }

        public Criteria andSuffixTimeFormatLike(String value) {
            addCriterion("SUFFIX_TIME_FORMAT like", value, "suffixTimeFormat");
            return (Criteria) this;
        }

        public Criteria andSuffixTimeFormatNotLike(String value) {
            addCriterion("SUFFIX_TIME_FORMAT not like", value, "suffixTimeFormat");
            return (Criteria) this;
        }

        public Criteria andSuffixTimeFormatIn(List<String> values) {
            addCriterion("SUFFIX_TIME_FORMAT in", values, "suffixTimeFormat");
            return (Criteria) this;
        }

        public Criteria andSuffixTimeFormatNotIn(List<String> values) {
            addCriterion("SUFFIX_TIME_FORMAT not in", values, "suffixTimeFormat");
            return (Criteria) this;
        }

        public Criteria andSuffixTimeFormatBetween(String value1, String value2) {
            addCriterion("SUFFIX_TIME_FORMAT between", value1, value2, "suffixTimeFormat");
            return (Criteria) this;
        }

        public Criteria andSuffixTimeFormatNotBetween(String value1, String value2) {
            addCriterion("SUFFIX_TIME_FORMAT not between", value1, value2, "suffixTimeFormat");
            return (Criteria) this;
        }

        public Criteria andSuffixDisranDirIsNull() {
            addCriterion("SUFFIX_DISRAN_DIR is null");
            return (Criteria) this;
        }

        public Criteria andSuffixDisranDirIsNotNull() {
            addCriterion("SUFFIX_DISRAN_DIR is not null");
            return (Criteria) this;
        }

        public Criteria andSuffixDisranDirEqualTo(String value) {
            addCriterion("SUFFIX_DISRAN_DIR =", value, "suffixDisranDir");
            return (Criteria) this;
        }

        public Criteria andSuffixDisranDirNotEqualTo(String value) {
            addCriterion("SUFFIX_DISRAN_DIR <>", value, "suffixDisranDir");
            return (Criteria) this;
        }

        public Criteria andSuffixDisranDirGreaterThan(String value) {
            addCriterion("SUFFIX_DISRAN_DIR >", value, "suffixDisranDir");
            return (Criteria) this;
        }

        public Criteria andSuffixDisranDirGreaterThanOrEqualTo(String value) {
            addCriterion("SUFFIX_DISRAN_DIR >=", value, "suffixDisranDir");
            return (Criteria) this;
        }

        public Criteria andSuffixDisranDirLessThan(String value) {
            addCriterion("SUFFIX_DISRAN_DIR <", value, "suffixDisranDir");
            return (Criteria) this;
        }

        public Criteria andSuffixDisranDirLessThanOrEqualTo(String value) {
            addCriterion("SUFFIX_DISRAN_DIR <=", value, "suffixDisranDir");
            return (Criteria) this;
        }

        public Criteria andSuffixDisranDirLike(String value) {
            addCriterion("SUFFIX_DISRAN_DIR like", value, "suffixDisranDir");
            return (Criteria) this;
        }

        public Criteria andSuffixDisranDirNotLike(String value) {
            addCriterion("SUFFIX_DISRAN_DIR not like", value, "suffixDisranDir");
            return (Criteria) this;
        }

        public Criteria andSuffixDisranDirIn(List<String> values) {
            addCriterion("SUFFIX_DISRAN_DIR in", values, "suffixDisranDir");
            return (Criteria) this;
        }

        public Criteria andSuffixDisranDirNotIn(List<String> values) {
            addCriterion("SUFFIX_DISRAN_DIR not in", values, "suffixDisranDir");
            return (Criteria) this;
        }

        public Criteria andSuffixDisranDirBetween(String value1, String value2) {
            addCriterion("SUFFIX_DISRAN_DIR between", value1, value2, "suffixDisranDir");
            return (Criteria) this;
        }

        public Criteria andSuffixDisranDirNotBetween(String value1, String value2) {
            addCriterion("SUFFIX_DISRAN_DIR not between", value1, value2, "suffixDisranDir");
            return (Criteria) this;
        }

        public Criteria andSuffixLocalDirIsNull() {
            addCriterion("SUFFIX_LOCAL_DIR is null");
            return (Criteria) this;
        }

        public Criteria andSuffixLocalDirIsNotNull() {
            addCriterion("SUFFIX_LOCAL_DIR is not null");
            return (Criteria) this;
        }

        public Criteria andSuffixLocalDirEqualTo(String value) {
            addCriterion("SUFFIX_LOCAL_DIR =", value, "suffixLocalDir");
            return (Criteria) this;
        }

        public Criteria andSuffixLocalDirNotEqualTo(String value) {
            addCriterion("SUFFIX_LOCAL_DIR <>", value, "suffixLocalDir");
            return (Criteria) this;
        }

        public Criteria andSuffixLocalDirGreaterThan(String value) {
            addCriterion("SUFFIX_LOCAL_DIR >", value, "suffixLocalDir");
            return (Criteria) this;
        }

        public Criteria andSuffixLocalDirGreaterThanOrEqualTo(String value) {
            addCriterion("SUFFIX_LOCAL_DIR >=", value, "suffixLocalDir");
            return (Criteria) this;
        }

        public Criteria andSuffixLocalDirLessThan(String value) {
            addCriterion("SUFFIX_LOCAL_DIR <", value, "suffixLocalDir");
            return (Criteria) this;
        }

        public Criteria andSuffixLocalDirLessThanOrEqualTo(String value) {
            addCriterion("SUFFIX_LOCAL_DIR <=", value, "suffixLocalDir");
            return (Criteria) this;
        }

        public Criteria andSuffixLocalDirLike(String value) {
            addCriterion("SUFFIX_LOCAL_DIR like", value, "suffixLocalDir");
            return (Criteria) this;
        }

        public Criteria andSuffixLocalDirNotLike(String value) {
            addCriterion("SUFFIX_LOCAL_DIR not like", value, "suffixLocalDir");
            return (Criteria) this;
        }

        public Criteria andSuffixLocalDirIn(List<String> values) {
            addCriterion("SUFFIX_LOCAL_DIR in", values, "suffixLocalDir");
            return (Criteria) this;
        }

        public Criteria andSuffixLocalDirNotIn(List<String> values) {
            addCriterion("SUFFIX_LOCAL_DIR not in", values, "suffixLocalDir");
            return (Criteria) this;
        }

        public Criteria andSuffixLocalDirBetween(String value1, String value2) {
            addCriterion("SUFFIX_LOCAL_DIR between", value1, value2, "suffixLocalDir");
            return (Criteria) this;
        }

        public Criteria andSuffixLocalDirNotBetween(String value1, String value2) {
            addCriterion("SUFFIX_LOCAL_DIR not between", value1, value2, "suffixLocalDir");
            return (Criteria) this;
        }

        public Criteria andFinishFlagIsNull() {
            addCriterion("FINISH_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andFinishFlagIsNotNull() {
            addCriterion("FINISH_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andFinishFlagEqualTo(String value) {
            addCriterion("FINISH_FLAG =", value, "finishFlag");
            return (Criteria) this;
        }

        public Criteria andFinishFlagNotEqualTo(String value) {
            addCriterion("FINISH_FLAG <>", value, "finishFlag");
            return (Criteria) this;
        }

        public Criteria andFinishFlagGreaterThan(String value) {
            addCriterion("FINISH_FLAG >", value, "finishFlag");
            return (Criteria) this;
        }

        public Criteria andFinishFlagGreaterThanOrEqualTo(String value) {
            addCriterion("FINISH_FLAG >=", value, "finishFlag");
            return (Criteria) this;
        }

        public Criteria andFinishFlagLessThan(String value) {
            addCriterion("FINISH_FLAG <", value, "finishFlag");
            return (Criteria) this;
        }

        public Criteria andFinishFlagLessThanOrEqualTo(String value) {
            addCriterion("FINISH_FLAG <=", value, "finishFlag");
            return (Criteria) this;
        }

        public Criteria andFinishFlagLike(String value) {
            addCriterion("FINISH_FLAG like", value, "finishFlag");
            return (Criteria) this;
        }

        public Criteria andFinishFlagNotLike(String value) {
            addCriterion("FINISH_FLAG not like", value, "finishFlag");
            return (Criteria) this;
        }

        public Criteria andFinishFlagIn(List<String> values) {
            addCriterion("FINISH_FLAG in", values, "finishFlag");
            return (Criteria) this;
        }

        public Criteria andFinishFlagNotIn(List<String> values) {
            addCriterion("FINISH_FLAG not in", values, "finishFlag");
            return (Criteria) this;
        }

        public Criteria andFinishFlagBetween(String value1, String value2) {
            addCriterion("FINISH_FLAG between", value1, value2, "finishFlag");
            return (Criteria) this;
        }

        public Criteria andFinishFlagNotBetween(String value1, String value2) {
            addCriterion("FINISH_FLAG not between", value1, value2, "finishFlag");
            return (Criteria) this;
        }

        public Criteria andShellStatementIsNull() {
            addCriterion("SHELL_STATEMENT is null");
            return (Criteria) this;
        }

        public Criteria andShellStatementIsNotNull() {
            addCriterion("SHELL_STATEMENT is not null");
            return (Criteria) this;
        }

        public Criteria andShellStatementEqualTo(String value) {
            addCriterion("SHELL_STATEMENT =", value, "shellStatement");
            return (Criteria) this;
        }

        public Criteria andShellStatementNotEqualTo(String value) {
            addCriterion("SHELL_STATEMENT <>", value, "shellStatement");
            return (Criteria) this;
        }

        public Criteria andShellStatementGreaterThan(String value) {
            addCriterion("SHELL_STATEMENT >", value, "shellStatement");
            return (Criteria) this;
        }

        public Criteria andShellStatementGreaterThanOrEqualTo(String value) {
            addCriterion("SHELL_STATEMENT >=", value, "shellStatement");
            return (Criteria) this;
        }

        public Criteria andShellStatementLessThan(String value) {
            addCriterion("SHELL_STATEMENT <", value, "shellStatement");
            return (Criteria) this;
        }

        public Criteria andShellStatementLessThanOrEqualTo(String value) {
            addCriterion("SHELL_STATEMENT <=", value, "shellStatement");
            return (Criteria) this;
        }

        public Criteria andShellStatementLike(String value) {
            addCriterion("SHELL_STATEMENT like", value, "shellStatement");
            return (Criteria) this;
        }

        public Criteria andShellStatementNotLike(String value) {
            addCriterion("SHELL_STATEMENT not like", value, "shellStatement");
            return (Criteria) this;
        }

        public Criteria andShellStatementIn(List<String> values) {
            addCriterion("SHELL_STATEMENT in", values, "shellStatement");
            return (Criteria) this;
        }

        public Criteria andShellStatementNotIn(List<String> values) {
            addCriterion("SHELL_STATEMENT not in", values, "shellStatement");
            return (Criteria) this;
        }

        public Criteria andShellStatementBetween(String value1, String value2) {
            addCriterion("SHELL_STATEMENT between", value1, value2, "shellStatement");
            return (Criteria) this;
        }

        public Criteria andShellStatementNotBetween(String value1, String value2) {
            addCriterion("SHELL_STATEMENT not between", value1, value2, "shellStatement");
            return (Criteria) this;
        }

        public Criteria andShellParametersIsNull() {
            addCriterion("SHELL_PARAMETERS is null");
            return (Criteria) this;
        }

        public Criteria andShellParametersIsNotNull() {
            addCriterion("SHELL_PARAMETERS is not null");
            return (Criteria) this;
        }

        public Criteria andShellParametersEqualTo(String value) {
            addCriterion("SHELL_PARAMETERS =", value, "shellParameters");
            return (Criteria) this;
        }

        public Criteria andShellParametersNotEqualTo(String value) {
            addCriterion("SHELL_PARAMETERS <>", value, "shellParameters");
            return (Criteria) this;
        }

        public Criteria andShellParametersGreaterThan(String value) {
            addCriterion("SHELL_PARAMETERS >", value, "shellParameters");
            return (Criteria) this;
        }

        public Criteria andShellParametersGreaterThanOrEqualTo(String value) {
            addCriterion("SHELL_PARAMETERS >=", value, "shellParameters");
            return (Criteria) this;
        }

        public Criteria andShellParametersLessThan(String value) {
            addCriterion("SHELL_PARAMETERS <", value, "shellParameters");
            return (Criteria) this;
        }

        public Criteria andShellParametersLessThanOrEqualTo(String value) {
            addCriterion("SHELL_PARAMETERS <=", value, "shellParameters");
            return (Criteria) this;
        }

        public Criteria andShellParametersLike(String value) {
            addCriterion("SHELL_PARAMETERS like", value, "shellParameters");
            return (Criteria) this;
        }

        public Criteria andShellParametersNotLike(String value) {
            addCriterion("SHELL_PARAMETERS not like", value, "shellParameters");
            return (Criteria) this;
        }

        public Criteria andShellParametersIn(List<String> values) {
            addCriterion("SHELL_PARAMETERS in", values, "shellParameters");
            return (Criteria) this;
        }

        public Criteria andShellParametersNotIn(List<String> values) {
            addCriterion("SHELL_PARAMETERS not in", values, "shellParameters");
            return (Criteria) this;
        }

        public Criteria andShellParametersBetween(String value1, String value2) {
            addCriterion("SHELL_PARAMETERS between", value1, value2, "shellParameters");
            return (Criteria) this;
        }

        public Criteria andShellParametersNotBetween(String value1, String value2) {
            addCriterion("SHELL_PARAMETERS not between", value1, value2, "shellParameters");
            return (Criteria) this;
        }

        public Criteria andInvokeShellModeIsNull() {
            addCriterion("INVOKE_SHELL_MODE is null");
            return (Criteria) this;
        }

        public Criteria andInvokeShellModeIsNotNull() {
            addCriterion("INVOKE_SHELL_MODE is not null");
            return (Criteria) this;
        }

        public Criteria andInvokeShellModeEqualTo(String value) {
            addCriterion("INVOKE_SHELL_MODE =", value, "invokeShellMode");
            return (Criteria) this;
        }

        public Criteria andInvokeShellModeNotEqualTo(String value) {
            addCriterion("INVOKE_SHELL_MODE <>", value, "invokeShellMode");
            return (Criteria) this;
        }

        public Criteria andInvokeShellModeGreaterThan(String value) {
            addCriterion("INVOKE_SHELL_MODE >", value, "invokeShellMode");
            return (Criteria) this;
        }

        public Criteria andInvokeShellModeGreaterThanOrEqualTo(String value) {
            addCriterion("INVOKE_SHELL_MODE >=", value, "invokeShellMode");
            return (Criteria) this;
        }

        public Criteria andInvokeShellModeLessThan(String value) {
            addCriterion("INVOKE_SHELL_MODE <", value, "invokeShellMode");
            return (Criteria) this;
        }

        public Criteria andInvokeShellModeLessThanOrEqualTo(String value) {
            addCriterion("INVOKE_SHELL_MODE <=", value, "invokeShellMode");
            return (Criteria) this;
        }

        public Criteria andInvokeShellModeLike(String value) {
            addCriterion("INVOKE_SHELL_MODE like", value, "invokeShellMode");
            return (Criteria) this;
        }

        public Criteria andInvokeShellModeNotLike(String value) {
            addCriterion("INVOKE_SHELL_MODE not like", value, "invokeShellMode");
            return (Criteria) this;
        }

        public Criteria andInvokeShellModeIn(List<String> values) {
            addCriterion("INVOKE_SHELL_MODE in", values, "invokeShellMode");
            return (Criteria) this;
        }

        public Criteria andInvokeShellModeNotIn(List<String> values) {
            addCriterion("INVOKE_SHELL_MODE not in", values, "invokeShellMode");
            return (Criteria) this;
        }

        public Criteria andInvokeShellModeBetween(String value1, String value2) {
            addCriterion("INVOKE_SHELL_MODE between", value1, value2, "invokeShellMode");
            return (Criteria) this;
        }

        public Criteria andInvokeShellModeNotBetween(String value1, String value2) {
            addCriterion("INVOKE_SHELL_MODE not between", value1, value2, "invokeShellMode");
            return (Criteria) this;
        }

        public Criteria andSshUserIsNull() {
            addCriterion("SSH_USER is null");
            return (Criteria) this;
        }

        public Criteria andSshUserIsNotNull() {
            addCriterion("SSH_USER is not null");
            return (Criteria) this;
        }

        public Criteria andSshUserEqualTo(String value) {
            addCriterion("SSH_USER =", value, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserNotEqualTo(String value) {
            addCriterion("SSH_USER <>", value, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserGreaterThan(String value) {
            addCriterion("SSH_USER >", value, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserGreaterThanOrEqualTo(String value) {
            addCriterion("SSH_USER >=", value, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserLessThan(String value) {
            addCriterion("SSH_USER <", value, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserLessThanOrEqualTo(String value) {
            addCriterion("SSH_USER <=", value, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserLike(String value) {
            addCriterion("SSH_USER like", value, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserNotLike(String value) {
            addCriterion("SSH_USER not like", value, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserIn(List<String> values) {
            addCriterion("SSH_USER in", values, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserNotIn(List<String> values) {
            addCriterion("SSH_USER not in", values, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserBetween(String value1, String value2) {
            addCriterion("SSH_USER between", value1, value2, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshUserNotBetween(String value1, String value2) {
            addCriterion("SSH_USER not between", value1, value2, "sshUser");
            return (Criteria) this;
        }

        public Criteria andSshPwdIsNull() {
            addCriterion("SSH_PWD is null");
            return (Criteria) this;
        }

        public Criteria andSshPwdIsNotNull() {
            addCriterion("SSH_PWD is not null");
            return (Criteria) this;
        }

        public Criteria andSshPwdEqualTo(String value) {
            addCriterion("SSH_PWD =", value, "sshPwd");
            return (Criteria) this;
        }

        public Criteria andSshPwdNotEqualTo(String value) {
            addCriterion("SSH_PWD <>", value, "sshPwd");
            return (Criteria) this;
        }

        public Criteria andSshPwdGreaterThan(String value) {
            addCriterion("SSH_PWD >", value, "sshPwd");
            return (Criteria) this;
        }

        public Criteria andSshPwdGreaterThanOrEqualTo(String value) {
            addCriterion("SSH_PWD >=", value, "sshPwd");
            return (Criteria) this;
        }

        public Criteria andSshPwdLessThan(String value) {
            addCriterion("SSH_PWD <", value, "sshPwd");
            return (Criteria) this;
        }

        public Criteria andSshPwdLessThanOrEqualTo(String value) {
            addCriterion("SSH_PWD <=", value, "sshPwd");
            return (Criteria) this;
        }

        public Criteria andSshPwdLike(String value) {
            addCriterion("SSH_PWD like", value, "sshPwd");
            return (Criteria) this;
        }

        public Criteria andSshPwdNotLike(String value) {
            addCriterion("SSH_PWD not like", value, "sshPwd");
            return (Criteria) this;
        }

        public Criteria andSshPwdIn(List<String> values) {
            addCriterion("SSH_PWD in", values, "sshPwd");
            return (Criteria) this;
        }

        public Criteria andSshPwdNotIn(List<String> values) {
            addCriterion("SSH_PWD not in", values, "sshPwd");
            return (Criteria) this;
        }

        public Criteria andSshPwdBetween(String value1, String value2) {
            addCriterion("SSH_PWD between", value1, value2, "sshPwd");
            return (Criteria) this;
        }

        public Criteria andSshPwdNotBetween(String value1, String value2) {
            addCriterion("SSH_PWD not between", value1, value2, "sshPwd");
            return (Criteria) this;
        }

        public Criteria andSshHostIsNull() {
            addCriterion("SSH_HOST is null");
            return (Criteria) this;
        }

        public Criteria andSshHostIsNotNull() {
            addCriterion("SSH_HOST is not null");
            return (Criteria) this;
        }

        public Criteria andSshHostEqualTo(String value) {
            addCriterion("SSH_HOST =", value, "sshHost");
            return (Criteria) this;
        }

        public Criteria andSshHostNotEqualTo(String value) {
            addCriterion("SSH_HOST <>", value, "sshHost");
            return (Criteria) this;
        }

        public Criteria andSshHostGreaterThan(String value) {
            addCriterion("SSH_HOST >", value, "sshHost");
            return (Criteria) this;
        }

        public Criteria andSshHostGreaterThanOrEqualTo(String value) {
            addCriterion("SSH_HOST >=", value, "sshHost");
            return (Criteria) this;
        }

        public Criteria andSshHostLessThan(String value) {
            addCriterion("SSH_HOST <", value, "sshHost");
            return (Criteria) this;
        }

        public Criteria andSshHostLessThanOrEqualTo(String value) {
            addCriterion("SSH_HOST <=", value, "sshHost");
            return (Criteria) this;
        }

        public Criteria andSshHostLike(String value) {
            addCriterion("SSH_HOST like", value, "sshHost");
            return (Criteria) this;
        }

        public Criteria andSshHostNotLike(String value) {
            addCriterion("SSH_HOST not like", value, "sshHost");
            return (Criteria) this;
        }

        public Criteria andSshHostIn(List<String> values) {
            addCriterion("SSH_HOST in", values, "sshHost");
            return (Criteria) this;
        }

        public Criteria andSshHostNotIn(List<String> values) {
            addCriterion("SSH_HOST not in", values, "sshHost");
            return (Criteria) this;
        }

        public Criteria andSshHostBetween(String value1, String value2) {
            addCriterion("SSH_HOST between", value1, value2, "sshHost");
            return (Criteria) this;
        }

        public Criteria andSshHostNotBetween(String value1, String value2) {
            addCriterion("SSH_HOST not between", value1, value2, "sshHost");
            return (Criteria) this;
        }

        public Criteria andCurrentDtIsNull() {
            addCriterion("CURRENT_DT is null");
            return (Criteria) this;
        }

        public Criteria andCurrentDtIsNotNull() {
            addCriterion("CURRENT_DT is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentDtEqualTo(Date value) {
            addCriterion("CURRENT_DT =", value, "currentDt");
            return (Criteria) this;
        }

        public Criteria andCurrentDtNotEqualTo(Date value) {
            addCriterion("CURRENT_DT <>", value, "currentDt");
            return (Criteria) this;
        }

        public Criteria andCurrentDtGreaterThan(Date value) {
            addCriterion("CURRENT_DT >", value, "currentDt");
            return (Criteria) this;
        }

        public Criteria andCurrentDtGreaterThanOrEqualTo(Date value) {
            addCriterion("CURRENT_DT >=", value, "currentDt");
            return (Criteria) this;
        }

        public Criteria andCurrentDtLessThan(Date value) {
            addCriterion("CURRENT_DT <", value, "currentDt");
            return (Criteria) this;
        }

        public Criteria andCurrentDtLessThanOrEqualTo(Date value) {
            addCriterion("CURRENT_DT <=", value, "currentDt");
            return (Criteria) this;
        }

        public Criteria andCurrentDtIn(List<Date> values) {
            addCriterion("CURRENT_DT in", values, "currentDt");
            return (Criteria) this;
        }

        public Criteria andCurrentDtNotIn(List<Date> values) {
            addCriterion("CURRENT_DT not in", values, "currentDt");
            return (Criteria) this;
        }

        public Criteria andCurrentDtBetween(Date value1, Date value2) {
            addCriterion("CURRENT_DT between", value1, value2, "currentDt");
            return (Criteria) this;
        }

        public Criteria andCurrentDtNotBetween(Date value1, Date value2) {
            addCriterion("CURRENT_DT not between", value1, value2, "currentDt");
            return (Criteria) this;
        }

        public Criteria andLastDateIsNull() {
            addCriterion("LAST_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastDateIsNotNull() {
            addCriterion("LAST_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastDateEqualTo(Date value) {
            addCriterion("LAST_DATE =", value, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateNotEqualTo(Date value) {
            addCriterion("LAST_DATE <>", value, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateGreaterThan(Date value) {
            addCriterion("LAST_DATE >", value, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_DATE >=", value, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateLessThan(Date value) {
            addCriterion("LAST_DATE <", value, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_DATE <=", value, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateIn(List<Date> values) {
            addCriterion("LAST_DATE in", values, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateNotIn(List<Date> values) {
            addCriterion("LAST_DATE not in", values, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateBetween(Date value1, Date value2) {
            addCriterion("LAST_DATE between", value1, value2, "lastDate");
            return (Criteria) this;
        }

        public Criteria andLastDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_DATE not between", value1, value2, "lastDate");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andExeResultIsNull() {
            addCriterion("EXE_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andExeResultIsNotNull() {
            addCriterion("EXE_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andExeResultEqualTo(String value) {
            addCriterion("EXE_RESULT =", value, "exeResult");
            return (Criteria) this;
        }

        public Criteria andExeResultNotEqualTo(String value) {
            addCriterion("EXE_RESULT <>", value, "exeResult");
            return (Criteria) this;
        }

        public Criteria andExeResultGreaterThan(String value) {
            addCriterion("EXE_RESULT >", value, "exeResult");
            return (Criteria) this;
        }

        public Criteria andExeResultGreaterThanOrEqualTo(String value) {
            addCriterion("EXE_RESULT >=", value, "exeResult");
            return (Criteria) this;
        }

        public Criteria andExeResultLessThan(String value) {
            addCriterion("EXE_RESULT <", value, "exeResult");
            return (Criteria) this;
        }

        public Criteria andExeResultLessThanOrEqualTo(String value) {
            addCriterion("EXE_RESULT <=", value, "exeResult");
            return (Criteria) this;
        }

        public Criteria andExeResultLike(String value) {
            addCriterion("EXE_RESULT like", value, "exeResult");
            return (Criteria) this;
        }

        public Criteria andExeResultNotLike(String value) {
            addCriterion("EXE_RESULT not like", value, "exeResult");
            return (Criteria) this;
        }

        public Criteria andExeResultIn(List<String> values) {
            addCriterion("EXE_RESULT in", values, "exeResult");
            return (Criteria) this;
        }

        public Criteria andExeResultNotIn(List<String> values) {
            addCriterion("EXE_RESULT not in", values, "exeResult");
            return (Criteria) this;
        }

        public Criteria andExeResultBetween(String value1, String value2) {
            addCriterion("EXE_RESULT between", value1, value2, "exeResult");
            return (Criteria) this;
        }

        public Criteria andExeResultNotBetween(String value1, String value2) {
            addCriterion("EXE_RESULT not between", value1, value2, "exeResult");
            return (Criteria) this;
        }

        public Criteria andExeHistFlagIsNull() {
            addCriterion("EXE_HIST_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andExeHistFlagIsNotNull() {
            addCriterion("EXE_HIST_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andExeHistFlagEqualTo(String value) {
            addCriterion("EXE_HIST_FLAG =", value, "exeHistFlag");
            return (Criteria) this;
        }

        public Criteria andExeHistFlagNotEqualTo(String value) {
            addCriterion("EXE_HIST_FLAG <>", value, "exeHistFlag");
            return (Criteria) this;
        }

        public Criteria andExeHistFlagGreaterThan(String value) {
            addCriterion("EXE_HIST_FLAG >", value, "exeHistFlag");
            return (Criteria) this;
        }

        public Criteria andExeHistFlagGreaterThanOrEqualTo(String value) {
            addCriterion("EXE_HIST_FLAG >=", value, "exeHistFlag");
            return (Criteria) this;
        }

        public Criteria andExeHistFlagLessThan(String value) {
            addCriterion("EXE_HIST_FLAG <", value, "exeHistFlag");
            return (Criteria) this;
        }

        public Criteria andExeHistFlagLessThanOrEqualTo(String value) {
            addCriterion("EXE_HIST_FLAG <=", value, "exeHistFlag");
            return (Criteria) this;
        }

        public Criteria andExeHistFlagLike(String value) {
            addCriterion("EXE_HIST_FLAG like", value, "exeHistFlag");
            return (Criteria) this;
        }

        public Criteria andExeHistFlagNotLike(String value) {
            addCriterion("EXE_HIST_FLAG not like", value, "exeHistFlag");
            return (Criteria) this;
        }

        public Criteria andExeHistFlagIn(List<String> values) {
            addCriterion("EXE_HIST_FLAG in", values, "exeHistFlag");
            return (Criteria) this;
        }

        public Criteria andExeHistFlagNotIn(List<String> values) {
            addCriterion("EXE_HIST_FLAG not in", values, "exeHistFlag");
            return (Criteria) this;
        }

        public Criteria andExeHistFlagBetween(String value1, String value2) {
            addCriterion("EXE_HIST_FLAG between", value1, value2, "exeHistFlag");
            return (Criteria) this;
        }

        public Criteria andExeHistFlagNotBetween(String value1, String value2) {
            addCriterion("EXE_HIST_FLAG not between", value1, value2, "exeHistFlag");
            return (Criteria) this;
        }

        public Criteria andHsitDateIsNull() {
            addCriterion("HSIT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andHsitDateIsNotNull() {
            addCriterion("HSIT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andHsitDateEqualTo(String value) {
            addCriterion("HSIT_DATE =", value, "hsitDate");
            return (Criteria) this;
        }

        public Criteria andHsitDateNotEqualTo(String value) {
            addCriterion("HSIT_DATE <>", value, "hsitDate");
            return (Criteria) this;
        }

        public Criteria andHsitDateGreaterThan(String value) {
            addCriterion("HSIT_DATE >", value, "hsitDate");
            return (Criteria) this;
        }

        public Criteria andHsitDateGreaterThanOrEqualTo(String value) {
            addCriterion("HSIT_DATE >=", value, "hsitDate");
            return (Criteria) this;
        }

        public Criteria andHsitDateLessThan(String value) {
            addCriterion("HSIT_DATE <", value, "hsitDate");
            return (Criteria) this;
        }

        public Criteria andHsitDateLessThanOrEqualTo(String value) {
            addCriterion("HSIT_DATE <=", value, "hsitDate");
            return (Criteria) this;
        }

        public Criteria andHsitDateLike(String value) {
            addCriterion("HSIT_DATE like", value, "hsitDate");
            return (Criteria) this;
        }

        public Criteria andHsitDateNotLike(String value) {
            addCriterion("HSIT_DATE not like", value, "hsitDate");
            return (Criteria) this;
        }

        public Criteria andHsitDateIn(List<String> values) {
            addCriterion("HSIT_DATE in", values, "hsitDate");
            return (Criteria) this;
        }

        public Criteria andHsitDateNotIn(List<String> values) {
            addCriterion("HSIT_DATE not in", values, "hsitDate");
            return (Criteria) this;
        }

        public Criteria andHsitDateBetween(String value1, String value2) {
            addCriterion("HSIT_DATE between", value1, value2, "hsitDate");
            return (Criteria) this;
        }

        public Criteria andHsitDateNotBetween(String value1, String value2) {
            addCriterion("HSIT_DATE not between", value1, value2, "hsitDate");
            return (Criteria) this;
        }

        public Criteria andShellConfigPropertiesIsNull() {
            addCriterion("SHELL_CONFIG_PROPERTIES is null");
            return (Criteria) this;
        }

        public Criteria andShellConfigPropertiesIsNotNull() {
            addCriterion("SHELL_CONFIG_PROPERTIES is not null");
            return (Criteria) this;
        }

        public Criteria andShellConfigPropertiesEqualTo(String value) {
            addCriterion("SHELL_CONFIG_PROPERTIES =", value, "shellConfigProperties");
            return (Criteria) this;
        }

        public Criteria andShellConfigPropertiesNotEqualTo(String value) {
            addCriterion("SHELL_CONFIG_PROPERTIES <>", value, "shellConfigProperties");
            return (Criteria) this;
        }

        public Criteria andShellConfigPropertiesGreaterThan(String value) {
            addCriterion("SHELL_CONFIG_PROPERTIES >", value, "shellConfigProperties");
            return (Criteria) this;
        }

        public Criteria andShellConfigPropertiesGreaterThanOrEqualTo(String value) {
            addCriterion("SHELL_CONFIG_PROPERTIES >=", value, "shellConfigProperties");
            return (Criteria) this;
        }

        public Criteria andShellConfigPropertiesLessThan(String value) {
            addCriterion("SHELL_CONFIG_PROPERTIES <", value, "shellConfigProperties");
            return (Criteria) this;
        }

        public Criteria andShellConfigPropertiesLessThanOrEqualTo(String value) {
            addCriterion("SHELL_CONFIG_PROPERTIES <=", value, "shellConfigProperties");
            return (Criteria) this;
        }

        public Criteria andShellConfigPropertiesLike(String value) {
            addCriterion("SHELL_CONFIG_PROPERTIES like", value, "shellConfigProperties");
            return (Criteria) this;
        }

        public Criteria andShellConfigPropertiesNotLike(String value) {
            addCriterion("SHELL_CONFIG_PROPERTIES not like", value, "shellConfigProperties");
            return (Criteria) this;
        }

        public Criteria andShellConfigPropertiesIn(List<String> values) {
            addCriterion("SHELL_CONFIG_PROPERTIES in", values, "shellConfigProperties");
            return (Criteria) this;
        }

        public Criteria andShellConfigPropertiesNotIn(List<String> values) {
            addCriterion("SHELL_CONFIG_PROPERTIES not in", values, "shellConfigProperties");
            return (Criteria) this;
        }

        public Criteria andShellConfigPropertiesBetween(String value1, String value2) {
            addCriterion("SHELL_CONFIG_PROPERTIES between", value1, value2, "shellConfigProperties");
            return (Criteria) this;
        }

        public Criteria andShellConfigPropertiesNotBetween(String value1, String value2) {
            addCriterion("SHELL_CONFIG_PROPERTIES not between", value1, value2, "shellConfigProperties");
            return (Criteria) this;
        }

        public Criteria andJavaClassNameIsNull() {
            addCriterion("JAVA_CLASS_NAME is null");
            return (Criteria) this;
        }

        public Criteria andJavaClassNameIsNotNull() {
            addCriterion("JAVA_CLASS_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andJavaClassNameEqualTo(String value) {
            addCriterion("JAVA_CLASS_NAME =", value, "javaClassName");
            return (Criteria) this;
        }

        public Criteria andJavaClassNameNotEqualTo(String value) {
            addCriterion("JAVA_CLASS_NAME <>", value, "javaClassName");
            return (Criteria) this;
        }

        public Criteria andJavaClassNameGreaterThan(String value) {
            addCriterion("JAVA_CLASS_NAME >", value, "javaClassName");
            return (Criteria) this;
        }

        public Criteria andJavaClassNameGreaterThanOrEqualTo(String value) {
            addCriterion("JAVA_CLASS_NAME >=", value, "javaClassName");
            return (Criteria) this;
        }

        public Criteria andJavaClassNameLessThan(String value) {
            addCriterion("JAVA_CLASS_NAME <", value, "javaClassName");
            return (Criteria) this;
        }

        public Criteria andJavaClassNameLessThanOrEqualTo(String value) {
            addCriterion("JAVA_CLASS_NAME <=", value, "javaClassName");
            return (Criteria) this;
        }

        public Criteria andJavaClassNameLike(String value) {
            addCriterion("JAVA_CLASS_NAME like", value, "javaClassName");
            return (Criteria) this;
        }

        public Criteria andJavaClassNameNotLike(String value) {
            addCriterion("JAVA_CLASS_NAME not like", value, "javaClassName");
            return (Criteria) this;
        }

        public Criteria andJavaClassNameIn(List<String> values) {
            addCriterion("JAVA_CLASS_NAME in", values, "javaClassName");
            return (Criteria) this;
        }

        public Criteria andJavaClassNameNotIn(List<String> values) {
            addCriterion("JAVA_CLASS_NAME not in", values, "javaClassName");
            return (Criteria) this;
        }

        public Criteria andJavaClassNameBetween(String value1, String value2) {
            addCriterion("JAVA_CLASS_NAME between", value1, value2, "javaClassName");
            return (Criteria) this;
        }

        public Criteria andJavaClassNameNotBetween(String value1, String value2) {
            addCriterion("JAVA_CLASS_NAME not between", value1, value2, "javaClassName");
            return (Criteria) this;
        }

        public Criteria andJavaMethodNameIsNull() {
            addCriterion("JAVA_METHOD_NAME is null");
            return (Criteria) this;
        }

        public Criteria andJavaMethodNameIsNotNull() {
            addCriterion("JAVA_METHOD_NAME is not null");
            return (Criteria) this;
        }

        public Criteria andJavaMethodNameEqualTo(String value) {
            addCriterion("JAVA_METHOD_NAME =", value, "javaMethodName");
            return (Criteria) this;
        }

        public Criteria andJavaMethodNameNotEqualTo(String value) {
            addCriterion("JAVA_METHOD_NAME <>", value, "javaMethodName");
            return (Criteria) this;
        }

        public Criteria andJavaMethodNameGreaterThan(String value) {
            addCriterion("JAVA_METHOD_NAME >", value, "javaMethodName");
            return (Criteria) this;
        }

        public Criteria andJavaMethodNameGreaterThanOrEqualTo(String value) {
            addCriterion("JAVA_METHOD_NAME >=", value, "javaMethodName");
            return (Criteria) this;
        }

        public Criteria andJavaMethodNameLessThan(String value) {
            addCriterion("JAVA_METHOD_NAME <", value, "javaMethodName");
            return (Criteria) this;
        }

        public Criteria andJavaMethodNameLessThanOrEqualTo(String value) {
            addCriterion("JAVA_METHOD_NAME <=", value, "javaMethodName");
            return (Criteria) this;
        }

        public Criteria andJavaMethodNameLike(String value) {
            addCriterion("JAVA_METHOD_NAME like", value, "javaMethodName");
            return (Criteria) this;
        }

        public Criteria andJavaMethodNameNotLike(String value) {
            addCriterion("JAVA_METHOD_NAME not like", value, "javaMethodName");
            return (Criteria) this;
        }

        public Criteria andJavaMethodNameIn(List<String> values) {
            addCriterion("JAVA_METHOD_NAME in", values, "javaMethodName");
            return (Criteria) this;
        }

        public Criteria andJavaMethodNameNotIn(List<String> values) {
            addCriterion("JAVA_METHOD_NAME not in", values, "javaMethodName");
            return (Criteria) this;
        }

        public Criteria andJavaMethodNameBetween(String value1, String value2) {
            addCriterion("JAVA_METHOD_NAME between", value1, value2, "javaMethodName");
            return (Criteria) this;
        }

        public Criteria andJavaMethodNameNotBetween(String value1, String value2) {
            addCriterion("JAVA_METHOD_NAME not between", value1, value2, "javaMethodName");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated do_not_delete_during_merge Tue Nov 29 14:18:05 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JCM_JOB_INFO
     *
     * @mbggenerated Tue Nov 29 14:18:05 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}