package org.hf.jsem.entity;

public class JcmJobInfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.JOB_CD
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String jobCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.JOB_NAME
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String jobName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.FTP_ADR
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String ftpAdr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.FTP_USER
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String ftpUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.FTP_PWD
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String ftpPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.LOCAL_DIR
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String localDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.DISTAN_DIR
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String distanDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.WORK_TYPE
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String workType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.OK_FILE_NAME
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String okFileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.CONENT_FILE_NAME
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String conentFileName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.SUFFFIX
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String sufffix;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.SUFFIX_TIME_FORMAT
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String suffixTimeFormat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.SUFFIX_DISRAN_DIR
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String suffixDisranDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.SUFFIX_LOCAL_DIR
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String suffixLocalDir;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.FINISH_FLAG
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String finishFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.SHELL_STATEMENT
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String shellStatement;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.SHELL_PARAMETERS
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String shellParameters;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.INVOKE_SHELL_MODE
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String invokeShellMode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.SSH_USER
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String sshUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.SSH_PWD
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String sshPwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_JOB_INFO.SSH_HOST
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    private String sshHost;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.JOB_CD
     *
     * @return the value of JCM_JOB_INFO.JOB_CD
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getJobCd() {
        return jobCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.JOB_CD
     *
     * @param jobCd the value for JCM_JOB_INFO.JOB_CD
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setJobCd(String jobCd) {
        this.jobCd = jobCd == null ? null : jobCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.JOB_NAME
     *
     * @return the value of JCM_JOB_INFO.JOB_NAME
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getJobName() {
        return jobName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.JOB_NAME
     *
     * @param jobName the value for JCM_JOB_INFO.JOB_NAME
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setJobName(String jobName) {
        this.jobName = jobName == null ? null : jobName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.FTP_ADR
     *
     * @return the value of JCM_JOB_INFO.FTP_ADR
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getFtpAdr() {
        return ftpAdr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.FTP_ADR
     *
     * @param ftpAdr the value for JCM_JOB_INFO.FTP_ADR
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setFtpAdr(String ftpAdr) {
        this.ftpAdr = ftpAdr == null ? null : ftpAdr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.FTP_USER
     *
     * @return the value of JCM_JOB_INFO.FTP_USER
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getFtpUser() {
        return ftpUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.FTP_USER
     *
     * @param ftpUser the value for JCM_JOB_INFO.FTP_USER
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setFtpUser(String ftpUser) {
        this.ftpUser = ftpUser == null ? null : ftpUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.FTP_PWD
     *
     * @return the value of JCM_JOB_INFO.FTP_PWD
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getFtpPwd() {
        return ftpPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.FTP_PWD
     *
     * @param ftpPwd the value for JCM_JOB_INFO.FTP_PWD
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setFtpPwd(String ftpPwd) {
        this.ftpPwd = ftpPwd == null ? null : ftpPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.LOCAL_DIR
     *
     * @return the value of JCM_JOB_INFO.LOCAL_DIR
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getLocalDir() {
        return localDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.LOCAL_DIR
     *
     * @param localDir the value for JCM_JOB_INFO.LOCAL_DIR
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setLocalDir(String localDir) {
        this.localDir = localDir == null ? null : localDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.DISTAN_DIR
     *
     * @return the value of JCM_JOB_INFO.DISTAN_DIR
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getDistanDir() {
        return distanDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.DISTAN_DIR
     *
     * @param distanDir the value for JCM_JOB_INFO.DISTAN_DIR
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setDistanDir(String distanDir) {
        this.distanDir = distanDir == null ? null : distanDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.WORK_TYPE
     *
     * @return the value of JCM_JOB_INFO.WORK_TYPE
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.WORK_TYPE
     *
     * @param workType the value for JCM_JOB_INFO.WORK_TYPE
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setWorkType(String workType) {
        this.workType = workType == null ? null : workType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.OK_FILE_NAME
     *
     * @return the value of JCM_JOB_INFO.OK_FILE_NAME
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getOkFileName() {
        return okFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.OK_FILE_NAME
     *
     * @param okFileName the value for JCM_JOB_INFO.OK_FILE_NAME
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setOkFileName(String okFileName) {
        this.okFileName = okFileName == null ? null : okFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.CONENT_FILE_NAME
     *
     * @return the value of JCM_JOB_INFO.CONENT_FILE_NAME
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getConentFileName() {
        return conentFileName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.CONENT_FILE_NAME
     *
     * @param conentFileName the value for JCM_JOB_INFO.CONENT_FILE_NAME
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setConentFileName(String conentFileName) {
        this.conentFileName = conentFileName == null ? null : conentFileName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.SUFFFIX
     *
     * @return the value of JCM_JOB_INFO.SUFFFIX
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getSufffix() {
        return sufffix;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.SUFFFIX
     *
     * @param sufffix the value for JCM_JOB_INFO.SUFFFIX
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setSufffix(String sufffix) {
        this.sufffix = sufffix == null ? null : sufffix.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.SUFFIX_TIME_FORMAT
     *
     * @return the value of JCM_JOB_INFO.SUFFIX_TIME_FORMAT
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getSuffixTimeFormat() {
        return suffixTimeFormat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.SUFFIX_TIME_FORMAT
     *
     * @param suffixTimeFormat the value for JCM_JOB_INFO.SUFFIX_TIME_FORMAT
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setSuffixTimeFormat(String suffixTimeFormat) {
        this.suffixTimeFormat = suffixTimeFormat == null ? null : suffixTimeFormat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.SUFFIX_DISRAN_DIR
     *
     * @return the value of JCM_JOB_INFO.SUFFIX_DISRAN_DIR
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getSuffixDisranDir() {
        return suffixDisranDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.SUFFIX_DISRAN_DIR
     *
     * @param suffixDisranDir the value for JCM_JOB_INFO.SUFFIX_DISRAN_DIR
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setSuffixDisranDir(String suffixDisranDir) {
        this.suffixDisranDir = suffixDisranDir == null ? null : suffixDisranDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.SUFFIX_LOCAL_DIR
     *
     * @return the value of JCM_JOB_INFO.SUFFIX_LOCAL_DIR
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getSuffixLocalDir() {
        return suffixLocalDir;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.SUFFIX_LOCAL_DIR
     *
     * @param suffixLocalDir the value for JCM_JOB_INFO.SUFFIX_LOCAL_DIR
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setSuffixLocalDir(String suffixLocalDir) {
        this.suffixLocalDir = suffixLocalDir == null ? null : suffixLocalDir.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.FINISH_FLAG
     *
     * @return the value of JCM_JOB_INFO.FINISH_FLAG
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getFinishFlag() {
        return finishFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.FINISH_FLAG
     *
     * @param finishFlag the value for JCM_JOB_INFO.FINISH_FLAG
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setFinishFlag(String finishFlag) {
        this.finishFlag = finishFlag == null ? null : finishFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.SHELL_STATEMENT
     *
     * @return the value of JCM_JOB_INFO.SHELL_STATEMENT
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getShellStatement() {
        return shellStatement;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.SHELL_STATEMENT
     *
     * @param shellStatement the value for JCM_JOB_INFO.SHELL_STATEMENT
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setShellStatement(String shellStatement) {
        this.shellStatement = shellStatement == null ? null : shellStatement.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.SHELL_PARAMETERS
     *
     * @return the value of JCM_JOB_INFO.SHELL_PARAMETERS
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getShellParameters() {
        return shellParameters;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.SHELL_PARAMETERS
     *
     * @param shellParameters the value for JCM_JOB_INFO.SHELL_PARAMETERS
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setShellParameters(String shellParameters) {
        this.shellParameters = shellParameters == null ? null : shellParameters.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.INVOKE_SHELL_MODE
     *
     * @return the value of JCM_JOB_INFO.INVOKE_SHELL_MODE
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getInvokeShellMode() {
        return invokeShellMode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.INVOKE_SHELL_MODE
     *
     * @param invokeShellMode the value for JCM_JOB_INFO.INVOKE_SHELL_MODE
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setInvokeShellMode(String invokeShellMode) {
        this.invokeShellMode = invokeShellMode == null ? null : invokeShellMode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.SSH_USER
     *
     * @return the value of JCM_JOB_INFO.SSH_USER
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getSshUser() {
        return sshUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.SSH_USER
     *
     * @param sshUser the value for JCM_JOB_INFO.SSH_USER
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setSshUser(String sshUser) {
        this.sshUser = sshUser == null ? null : sshUser.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.SSH_PWD
     *
     * @return the value of JCM_JOB_INFO.SSH_PWD
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getSshPwd() {
        return sshPwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.SSH_PWD
     *
     * @param sshPwd the value for JCM_JOB_INFO.SSH_PWD
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setSshPwd(String sshPwd) {
        this.sshPwd = sshPwd == null ? null : sshPwd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_JOB_INFO.SSH_HOST
     *
     * @return the value of JCM_JOB_INFO.SSH_HOST
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public String getSshHost() {
        return sshHost;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_JOB_INFO.SSH_HOST
     *
     * @param sshHost the value for JCM_JOB_INFO.SSH_HOST
     *
     * @mbggenerated Wed Nov 02 16:16:07 CST 2016
     */
    public void setSshHost(String sshHost) {
        this.sshHost = sshHost == null ? null : sshHost.trim();
    }
}