package org.hf.jsem.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class JcmProcessExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public JcmProcessExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andWorkTypeIsNull() {
            addCriterion("WORK_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIsNotNull() {
            addCriterion("WORK_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andWorkTypeEqualTo(String value) {
            addCriterion("WORK_TYPE =", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotEqualTo(String value) {
            addCriterion("WORK_TYPE <>", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeGreaterThan(String value) {
            addCriterion("WORK_TYPE >", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeGreaterThanOrEqualTo(String value) {
            addCriterion("WORK_TYPE >=", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLessThan(String value) {
            addCriterion("WORK_TYPE <", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLessThanOrEqualTo(String value) {
            addCriterion("WORK_TYPE <=", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeLike(String value) {
            addCriterion("WORK_TYPE like", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotLike(String value) {
            addCriterion("WORK_TYPE not like", value, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeIn(List<String> values) {
            addCriterion("WORK_TYPE in", values, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotIn(List<String> values) {
            addCriterion("WORK_TYPE not in", values, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeBetween(String value1, String value2) {
            addCriterion("WORK_TYPE between", value1, value2, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeNotBetween(String value1, String value2) {
            addCriterion("WORK_TYPE not between", value1, value2, "workType");
            return (Criteria) this;
        }

        public Criteria andWorkTypeDescIsNull() {
            addCriterion("WORK_TYPE_DESC is null");
            return (Criteria) this;
        }

        public Criteria andWorkTypeDescIsNotNull() {
            addCriterion("WORK_TYPE_DESC is not null");
            return (Criteria) this;
        }

        public Criteria andWorkTypeDescEqualTo(String value) {
            addCriterion("WORK_TYPE_DESC =", value, "workTypeDesc");
            return (Criteria) this;
        }

        public Criteria andWorkTypeDescNotEqualTo(String value) {
            addCriterion("WORK_TYPE_DESC <>", value, "workTypeDesc");
            return (Criteria) this;
        }

        public Criteria andWorkTypeDescGreaterThan(String value) {
            addCriterion("WORK_TYPE_DESC >", value, "workTypeDesc");
            return (Criteria) this;
        }

        public Criteria andWorkTypeDescGreaterThanOrEqualTo(String value) {
            addCriterion("WORK_TYPE_DESC >=", value, "workTypeDesc");
            return (Criteria) this;
        }

        public Criteria andWorkTypeDescLessThan(String value) {
            addCriterion("WORK_TYPE_DESC <", value, "workTypeDesc");
            return (Criteria) this;
        }

        public Criteria andWorkTypeDescLessThanOrEqualTo(String value) {
            addCriterion("WORK_TYPE_DESC <=", value, "workTypeDesc");
            return (Criteria) this;
        }

        public Criteria andWorkTypeDescLike(String value) {
            addCriterion("WORK_TYPE_DESC like", value, "workTypeDesc");
            return (Criteria) this;
        }

        public Criteria andWorkTypeDescNotLike(String value) {
            addCriterion("WORK_TYPE_DESC not like", value, "workTypeDesc");
            return (Criteria) this;
        }

        public Criteria andWorkTypeDescIn(List<String> values) {
            addCriterion("WORK_TYPE_DESC in", values, "workTypeDesc");
            return (Criteria) this;
        }

        public Criteria andWorkTypeDescNotIn(List<String> values) {
            addCriterion("WORK_TYPE_DESC not in", values, "workTypeDesc");
            return (Criteria) this;
        }

        public Criteria andWorkTypeDescBetween(String value1, String value2) {
            addCriterion("WORK_TYPE_DESC between", value1, value2, "workTypeDesc");
            return (Criteria) this;
        }

        public Criteria andWorkTypeDescNotBetween(String value1, String value2) {
            addCriterion("WORK_TYPE_DESC not between", value1, value2, "workTypeDesc");
            return (Criteria) this;
        }

        public Criteria andLastRunDateIsNull() {
            addCriterion("LAST_RUN_DATE is null");
            return (Criteria) this;
        }

        public Criteria andLastRunDateIsNotNull() {
            addCriterion("LAST_RUN_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andLastRunDateEqualTo(Date value) {
            addCriterion("LAST_RUN_DATE =", value, "lastRunDate");
            return (Criteria) this;
        }

        public Criteria andLastRunDateNotEqualTo(Date value) {
            addCriterion("LAST_RUN_DATE <>", value, "lastRunDate");
            return (Criteria) this;
        }

        public Criteria andLastRunDateGreaterThan(Date value) {
            addCriterion("LAST_RUN_DATE >", value, "lastRunDate");
            return (Criteria) this;
        }

        public Criteria andLastRunDateGreaterThanOrEqualTo(Date value) {
            addCriterion("LAST_RUN_DATE >=", value, "lastRunDate");
            return (Criteria) this;
        }

        public Criteria andLastRunDateLessThan(Date value) {
            addCriterion("LAST_RUN_DATE <", value, "lastRunDate");
            return (Criteria) this;
        }

        public Criteria andLastRunDateLessThanOrEqualTo(Date value) {
            addCriterion("LAST_RUN_DATE <=", value, "lastRunDate");
            return (Criteria) this;
        }

        public Criteria andLastRunDateIn(List<Date> values) {
            addCriterion("LAST_RUN_DATE in", values, "lastRunDate");
            return (Criteria) this;
        }

        public Criteria andLastRunDateNotIn(List<Date> values) {
            addCriterion("LAST_RUN_DATE not in", values, "lastRunDate");
            return (Criteria) this;
        }

        public Criteria andLastRunDateBetween(Date value1, Date value2) {
            addCriterion("LAST_RUN_DATE between", value1, value2, "lastRunDate");
            return (Criteria) this;
        }

        public Criteria andLastRunDateNotBetween(Date value1, Date value2) {
            addCriterion("LAST_RUN_DATE not between", value1, value2, "lastRunDate");
            return (Criteria) this;
        }

        public Criteria andCurrentDateIsNull() {
            addCriterion("CURRENT_DATE is null");
            return (Criteria) this;
        }

        public Criteria andCurrentDateIsNotNull() {
            addCriterion("CURRENT_DATE is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentDateEqualTo(Date value) {
            addCriterion("CURRENT_DATE =", value, "currentDate");
            return (Criteria) this;
        }

        public Criteria andCurrentDateNotEqualTo(Date value) {
            addCriterion("CURRENT_DATE <>", value, "currentDate");
            return (Criteria) this;
        }

        public Criteria andCurrentDateGreaterThan(Date value) {
            addCriterion("CURRENT_DATE >", value, "currentDate");
            return (Criteria) this;
        }

        public Criteria andCurrentDateGreaterThanOrEqualTo(Date value) {
            addCriterion("CURRENT_DATE >=", value, "currentDate");
            return (Criteria) this;
        }

        public Criteria andCurrentDateLessThan(Date value) {
            addCriterion("CURRENT_DATE <", value, "currentDate");
            return (Criteria) this;
        }

        public Criteria andCurrentDateLessThanOrEqualTo(Date value) {
            addCriterion("CURRENT_DATE <=", value, "currentDate");
            return (Criteria) this;
        }

        public Criteria andCurrentDateIn(List<Date> values) {
            addCriterion("CURRENT_DATE in", values, "currentDate");
            return (Criteria) this;
        }

        public Criteria andCurrentDateNotIn(List<Date> values) {
            addCriterion("CURRENT_DATE not in", values, "currentDate");
            return (Criteria) this;
        }

        public Criteria andCurrentDateBetween(Date value1, Date value2) {
            addCriterion("CURRENT_DATE between", value1, value2, "currentDate");
            return (Criteria) this;
        }

        public Criteria andCurrentDateNotBetween(Date value1, Date value2) {
            addCriterion("CURRENT_DATE not between", value1, value2, "currentDate");
            return (Criteria) this;
        }

        public Criteria andRunFlagIsNull() {
            addCriterion("RUN_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andRunFlagIsNotNull() {
            addCriterion("RUN_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andRunFlagEqualTo(String value) {
            addCriterion("RUN_FLAG =", value, "runFlag");
            return (Criteria) this;
        }

        public Criteria andRunFlagNotEqualTo(String value) {
            addCriterion("RUN_FLAG <>", value, "runFlag");
            return (Criteria) this;
        }

        public Criteria andRunFlagGreaterThan(String value) {
            addCriterion("RUN_FLAG >", value, "runFlag");
            return (Criteria) this;
        }

        public Criteria andRunFlagGreaterThanOrEqualTo(String value) {
            addCriterion("RUN_FLAG >=", value, "runFlag");
            return (Criteria) this;
        }

        public Criteria andRunFlagLessThan(String value) {
            addCriterion("RUN_FLAG <", value, "runFlag");
            return (Criteria) this;
        }

        public Criteria andRunFlagLessThanOrEqualTo(String value) {
            addCriterion("RUN_FLAG <=", value, "runFlag");
            return (Criteria) this;
        }

        public Criteria andRunFlagLike(String value) {
            addCriterion("RUN_FLAG like", value, "runFlag");
            return (Criteria) this;
        }

        public Criteria andRunFlagNotLike(String value) {
            addCriterion("RUN_FLAG not like", value, "runFlag");
            return (Criteria) this;
        }

        public Criteria andRunFlagIn(List<String> values) {
            addCriterion("RUN_FLAG in", values, "runFlag");
            return (Criteria) this;
        }

        public Criteria andRunFlagNotIn(List<String> values) {
            addCriterion("RUN_FLAG not in", values, "runFlag");
            return (Criteria) this;
        }

        public Criteria andRunFlagBetween(String value1, String value2) {
            addCriterion("RUN_FLAG between", value1, value2, "runFlag");
            return (Criteria) this;
        }

        public Criteria andRunFlagNotBetween(String value1, String value2) {
            addCriterion("RUN_FLAG not between", value1, value2, "runFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentFinishFlagIsNull() {
            addCriterion("CURRENT_FINISH_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andCurrentFinishFlagIsNotNull() {
            addCriterion("CURRENT_FINISH_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentFinishFlagEqualTo(String value) {
            addCriterion("CURRENT_FINISH_FLAG =", value, "currentFinishFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentFinishFlagNotEqualTo(String value) {
            addCriterion("CURRENT_FINISH_FLAG <>", value, "currentFinishFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentFinishFlagGreaterThan(String value) {
            addCriterion("CURRENT_FINISH_FLAG >", value, "currentFinishFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentFinishFlagGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENT_FINISH_FLAG >=", value, "currentFinishFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentFinishFlagLessThan(String value) {
            addCriterion("CURRENT_FINISH_FLAG <", value, "currentFinishFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentFinishFlagLessThanOrEqualTo(String value) {
            addCriterion("CURRENT_FINISH_FLAG <=", value, "currentFinishFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentFinishFlagLike(String value) {
            addCriterion("CURRENT_FINISH_FLAG like", value, "currentFinishFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentFinishFlagNotLike(String value) {
            addCriterion("CURRENT_FINISH_FLAG not like", value, "currentFinishFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentFinishFlagIn(List<String> values) {
            addCriterion("CURRENT_FINISH_FLAG in", values, "currentFinishFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentFinishFlagNotIn(List<String> values) {
            addCriterion("CURRENT_FINISH_FLAG not in", values, "currentFinishFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentFinishFlagBetween(String value1, String value2) {
            addCriterion("CURRENT_FINISH_FLAG between", value1, value2, "currentFinishFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentFinishFlagNotBetween(String value1, String value2) {
            addCriterion("CURRENT_FINISH_FLAG not between", value1, value2, "currentFinishFlag");
            return (Criteria) this;
        }

        public Criteria andCurrentRunInfoIsNull() {
            addCriterion("CURRENT_RUN_INFO is null");
            return (Criteria) this;
        }

        public Criteria andCurrentRunInfoIsNotNull() {
            addCriterion("CURRENT_RUN_INFO is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentRunInfoEqualTo(String value) {
            addCriterion("CURRENT_RUN_INFO =", value, "currentRunInfo");
            return (Criteria) this;
        }

        public Criteria andCurrentRunInfoNotEqualTo(String value) {
            addCriterion("CURRENT_RUN_INFO <>", value, "currentRunInfo");
            return (Criteria) this;
        }

        public Criteria andCurrentRunInfoGreaterThan(String value) {
            addCriterion("CURRENT_RUN_INFO >", value, "currentRunInfo");
            return (Criteria) this;
        }

        public Criteria andCurrentRunInfoGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENT_RUN_INFO >=", value, "currentRunInfo");
            return (Criteria) this;
        }

        public Criteria andCurrentRunInfoLessThan(String value) {
            addCriterion("CURRENT_RUN_INFO <", value, "currentRunInfo");
            return (Criteria) this;
        }

        public Criteria andCurrentRunInfoLessThanOrEqualTo(String value) {
            addCriterion("CURRENT_RUN_INFO <=", value, "currentRunInfo");
            return (Criteria) this;
        }

        public Criteria andCurrentRunInfoLike(String value) {
            addCriterion("CURRENT_RUN_INFO like", value, "currentRunInfo");
            return (Criteria) this;
        }

        public Criteria andCurrentRunInfoNotLike(String value) {
            addCriterion("CURRENT_RUN_INFO not like", value, "currentRunInfo");
            return (Criteria) this;
        }

        public Criteria andCurrentRunInfoIn(List<String> values) {
            addCriterion("CURRENT_RUN_INFO in", values, "currentRunInfo");
            return (Criteria) this;
        }

        public Criteria andCurrentRunInfoNotIn(List<String> values) {
            addCriterion("CURRENT_RUN_INFO not in", values, "currentRunInfo");
            return (Criteria) this;
        }

        public Criteria andCurrentRunInfoBetween(String value1, String value2) {
            addCriterion("CURRENT_RUN_INFO between", value1, value2, "currentRunInfo");
            return (Criteria) this;
        }

        public Criteria andCurrentRunInfoNotBetween(String value1, String value2) {
            addCriterion("CURRENT_RUN_INFO not between", value1, value2, "currentRunInfo");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andCurrentExeResultIsNull() {
            addCriterion("CURRENT_EXE_RESULT is null");
            return (Criteria) this;
        }

        public Criteria andCurrentExeResultIsNotNull() {
            addCriterion("CURRENT_EXE_RESULT is not null");
            return (Criteria) this;
        }

        public Criteria andCurrentExeResultEqualTo(String value) {
            addCriterion("CURRENT_EXE_RESULT =", value, "currentExeResult");
            return (Criteria) this;
        }

        public Criteria andCurrentExeResultNotEqualTo(String value) {
            addCriterion("CURRENT_EXE_RESULT <>", value, "currentExeResult");
            return (Criteria) this;
        }

        public Criteria andCurrentExeResultGreaterThan(String value) {
            addCriterion("CURRENT_EXE_RESULT >", value, "currentExeResult");
            return (Criteria) this;
        }

        public Criteria andCurrentExeResultGreaterThanOrEqualTo(String value) {
            addCriterion("CURRENT_EXE_RESULT >=", value, "currentExeResult");
            return (Criteria) this;
        }

        public Criteria andCurrentExeResultLessThan(String value) {
            addCriterion("CURRENT_EXE_RESULT <", value, "currentExeResult");
            return (Criteria) this;
        }

        public Criteria andCurrentExeResultLessThanOrEqualTo(String value) {
            addCriterion("CURRENT_EXE_RESULT <=", value, "currentExeResult");
            return (Criteria) this;
        }

        public Criteria andCurrentExeResultLike(String value) {
            addCriterion("CURRENT_EXE_RESULT like", value, "currentExeResult");
            return (Criteria) this;
        }

        public Criteria andCurrentExeResultNotLike(String value) {
            addCriterion("CURRENT_EXE_RESULT not like", value, "currentExeResult");
            return (Criteria) this;
        }

        public Criteria andCurrentExeResultIn(List<String> values) {
            addCriterion("CURRENT_EXE_RESULT in", values, "currentExeResult");
            return (Criteria) this;
        }

        public Criteria andCurrentExeResultNotIn(List<String> values) {
            addCriterion("CURRENT_EXE_RESULT not in", values, "currentExeResult");
            return (Criteria) this;
        }

        public Criteria andCurrentExeResultBetween(String value1, String value2) {
            addCriterion("CURRENT_EXE_RESULT between", value1, value2, "currentExeResult");
            return (Criteria) this;
        }

        public Criteria andCurrentExeResultNotBetween(String value1, String value2) {
            addCriterion("CURRENT_EXE_RESULT not between", value1, value2, "currentExeResult");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated do_not_delete_during_merge Mon Nov 28 15:05:12 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table JCM_PROCESS
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}