package org.hf.jsem.entity;

import java.util.Date;

public class JcmProcess {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_PROCESS.WORK_TYPE
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    private String workType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_PROCESS.WORK_TYPE_DESC
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    private String workTypeDesc;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_PROCESS.LAST_RUN_DATE
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    private Date lastRunDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_PROCESS.CURRENT_DATE
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    private Date currentDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_PROCESS.RUN_FLAG
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    private String runFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_PROCESS.CURRENT_FINISH_FLAG
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    private String currentFinishFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_PROCESS.CURRENT_RUN_INFO
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    private String currentRunInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_PROCESS.REMARK
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_PROCESS.CURRENT_EXE_RESULT
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    private String currentExeResult;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_PROCESS.WORK_TYPE
     *
     * @return the value of JCM_PROCESS.WORK_TYPE
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public String getWorkType() {
        return workType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_PROCESS.WORK_TYPE
     *
     * @param workType the value for JCM_PROCESS.WORK_TYPE
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public void setWorkType(String workType) {
        this.workType = workType == null ? null : workType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_PROCESS.WORK_TYPE_DESC
     *
     * @return the value of JCM_PROCESS.WORK_TYPE_DESC
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public String getWorkTypeDesc() {
        return workTypeDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_PROCESS.WORK_TYPE_DESC
     *
     * @param workTypeDesc the value for JCM_PROCESS.WORK_TYPE_DESC
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public void setWorkTypeDesc(String workTypeDesc) {
        this.workTypeDesc = workTypeDesc == null ? null : workTypeDesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_PROCESS.LAST_RUN_DATE
     *
     * @return the value of JCM_PROCESS.LAST_RUN_DATE
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public Date getLastRunDate() {
        return lastRunDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_PROCESS.LAST_RUN_DATE
     *
     * @param lastRunDate the value for JCM_PROCESS.LAST_RUN_DATE
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public void setLastRunDate(Date lastRunDate) {
        this.lastRunDate = lastRunDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_PROCESS.CURRENT_DATE
     *
     * @return the value of JCM_PROCESS.CURRENT_DATE
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public Date getCurrentDate() {
        return currentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_PROCESS.CURRENT_DATE
     *
     * @param currentDate the value for JCM_PROCESS.CURRENT_DATE
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public void setCurrentDate(Date currentDate) {
        this.currentDate = currentDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_PROCESS.RUN_FLAG
     *
     * @return the value of JCM_PROCESS.RUN_FLAG
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public String getRunFlag() {
        return runFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_PROCESS.RUN_FLAG
     *
     * @param runFlag the value for JCM_PROCESS.RUN_FLAG
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public void setRunFlag(String runFlag) {
        this.runFlag = runFlag == null ? null : runFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_PROCESS.CURRENT_FINISH_FLAG
     *
     * @return the value of JCM_PROCESS.CURRENT_FINISH_FLAG
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public String getCurrentFinishFlag() {
        return currentFinishFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_PROCESS.CURRENT_FINISH_FLAG
     *
     * @param currentFinishFlag the value for JCM_PROCESS.CURRENT_FINISH_FLAG
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public void setCurrentFinishFlag(String currentFinishFlag) {
        this.currentFinishFlag = currentFinishFlag == null ? null : currentFinishFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_PROCESS.CURRENT_RUN_INFO
     *
     * @return the value of JCM_PROCESS.CURRENT_RUN_INFO
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public String getCurrentRunInfo() {
        return currentRunInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_PROCESS.CURRENT_RUN_INFO
     *
     * @param currentRunInfo the value for JCM_PROCESS.CURRENT_RUN_INFO
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public void setCurrentRunInfo(String currentRunInfo) {
        this.currentRunInfo = currentRunInfo == null ? null : currentRunInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_PROCESS.REMARK
     *
     * @return the value of JCM_PROCESS.REMARK
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_PROCESS.REMARK
     *
     * @param remark the value for JCM_PROCESS.REMARK
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_PROCESS.CURRENT_EXE_RESULT
     *
     * @return the value of JCM_PROCESS.CURRENT_EXE_RESULT
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public String getCurrentExeResult() {
        return currentExeResult;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_PROCESS.CURRENT_EXE_RESULT
     *
     * @param currentExeResult the value for JCM_PROCESS.CURRENT_EXE_RESULT
     *
     * @mbggenerated Mon Nov 28 15:05:12 CST 2016
     */
    public void setCurrentExeResult(String currentExeResult) {
        this.currentExeResult = currentExeResult == null ? null : currentExeResult.trim();
    }
}