package org.hf.jsem.entity;

public class JcmTest {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column JCM_TEST.F_ID
     *
     * @mbggenerated Mon Oct 31 15:57:43 CST 2016
     */
    private String fId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column JCM_TEST.F_ID
     *
     * @return the value of JCM_TEST.F_ID
     *
     * @mbggenerated Mon Oct 31 15:57:43 CST 2016
     */
    public String getfId() {
        return fId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column JCM_TEST.F_ID
     *
     * @param fId the value for JCM_TEST.F_ID
     *
     * @mbggenerated Mon Oct 31 15:57:43 CST 2016
     */
    public void setfId(String fId) {
        this.fId = fId == null ? null : fId.trim();
    }
}