package org.hf.jsem.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SscfWorkMainExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 09 09:44:34 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 09 09:44:34 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 09 09:44:34 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 09 09:44:34 CST 2016
     */
    public SscfWorkMainExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 09 09:44:34 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 09 09:44:34 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 09 09:44:34 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 09 09:44:34 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 09 09:44:34 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 09 09:44:34 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 09 09:44:34 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 09 09:44:34 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 09 09:44:34 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 09 09:44:34 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 09 09:44:34 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andApplyNoIsNull() {
            addCriterion("APPLY_NO is null");
            return (Criteria) this;
        }

        public Criteria andApplyNoIsNotNull() {
            addCriterion("APPLY_NO is not null");
            return (Criteria) this;
        }

        public Criteria andApplyNoEqualTo(String value) {
            addCriterion("APPLY_NO =", value, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoNotEqualTo(String value) {
            addCriterion("APPLY_NO <>", value, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoGreaterThan(String value) {
            addCriterion("APPLY_NO >", value, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoGreaterThanOrEqualTo(String value) {
            addCriterion("APPLY_NO >=", value, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoLessThan(String value) {
            addCriterion("APPLY_NO <", value, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoLessThanOrEqualTo(String value) {
            addCriterion("APPLY_NO <=", value, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoLike(String value) {
            addCriterion("APPLY_NO like", value, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoNotLike(String value) {
            addCriterion("APPLY_NO not like", value, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoIn(List<String> values) {
            addCriterion("APPLY_NO in", values, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoNotIn(List<String> values) {
            addCriterion("APPLY_NO not in", values, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoBetween(String value1, String value2) {
            addCriterion("APPLY_NO between", value1, value2, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoNotBetween(String value1, String value2) {
            addCriterion("APPLY_NO not between", value1, value2, "applyNo");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("STATUS is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(String value) {
            addCriterion("STATUS =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(String value) {
            addCriterion("STATUS <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(String value) {
            addCriterion("STATUS >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(String value) {
            addCriterion("STATUS >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(String value) {
            addCriterion("STATUS <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(String value) {
            addCriterion("STATUS <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLike(String value) {
            addCriterion("STATUS like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotLike(String value) {
            addCriterion("STATUS not like", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<String> values) {
            addCriterion("STATUS in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<String> values) {
            addCriterion("STATUS not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(String value1, String value2) {
            addCriterion("STATUS between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(String value1, String value2) {
            addCriterion("STATUS not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andLnCatIsNull() {
            addCriterion("LN_CAT is null");
            return (Criteria) this;
        }

        public Criteria andLnCatIsNotNull() {
            addCriterion("LN_CAT is not null");
            return (Criteria) this;
        }

        public Criteria andLnCatEqualTo(String value) {
            addCriterion("LN_CAT =", value, "lnCat");
            return (Criteria) this;
        }

        public Criteria andLnCatNotEqualTo(String value) {
            addCriterion("LN_CAT <>", value, "lnCat");
            return (Criteria) this;
        }

        public Criteria andLnCatGreaterThan(String value) {
            addCriterion("LN_CAT >", value, "lnCat");
            return (Criteria) this;
        }

        public Criteria andLnCatGreaterThanOrEqualTo(String value) {
            addCriterion("LN_CAT >=", value, "lnCat");
            return (Criteria) this;
        }

        public Criteria andLnCatLessThan(String value) {
            addCriterion("LN_CAT <", value, "lnCat");
            return (Criteria) this;
        }

        public Criteria andLnCatLessThanOrEqualTo(String value) {
            addCriterion("LN_CAT <=", value, "lnCat");
            return (Criteria) this;
        }

        public Criteria andLnCatLike(String value) {
            addCriterion("LN_CAT like", value, "lnCat");
            return (Criteria) this;
        }

        public Criteria andLnCatNotLike(String value) {
            addCriterion("LN_CAT not like", value, "lnCat");
            return (Criteria) this;
        }

        public Criteria andLnCatIn(List<String> values) {
            addCriterion("LN_CAT in", values, "lnCat");
            return (Criteria) this;
        }

        public Criteria andLnCatNotIn(List<String> values) {
            addCriterion("LN_CAT not in", values, "lnCat");
            return (Criteria) this;
        }

        public Criteria andLnCatBetween(String value1, String value2) {
            addCriterion("LN_CAT between", value1, value2, "lnCat");
            return (Criteria) this;
        }

        public Criteria andLnCatNotBetween(String value1, String value2) {
            addCriterion("LN_CAT not between", value1, value2, "lnCat");
            return (Criteria) this;
        }

        public Criteria andApplIdIsNull() {
            addCriterion("APPL_ID is null");
            return (Criteria) this;
        }

        public Criteria andApplIdIsNotNull() {
            addCriterion("APPL_ID is not null");
            return (Criteria) this;
        }

        public Criteria andApplIdEqualTo(BigDecimal value) {
            addCriterion("APPL_ID =", value, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdNotEqualTo(BigDecimal value) {
            addCriterion("APPL_ID <>", value, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdGreaterThan(BigDecimal value) {
            addCriterion("APPL_ID >", value, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("APPL_ID >=", value, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdLessThan(BigDecimal value) {
            addCriterion("APPL_ID <", value, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("APPL_ID <=", value, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdIn(List<BigDecimal> values) {
            addCriterion("APPL_ID in", values, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdNotIn(List<BigDecimal> values) {
            addCriterion("APPL_ID not in", values, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("APPL_ID between", value1, value2, "applId");
            return (Criteria) this;
        }

        public Criteria andApplIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("APPL_ID not between", value1, value2, "applId");
            return (Criteria) this;
        }

        public Criteria andPrcsDtIsNull() {
            addCriterion("PRCS_DT is null");
            return (Criteria) this;
        }

        public Criteria andPrcsDtIsNotNull() {
            addCriterion("PRCS_DT is not null");
            return (Criteria) this;
        }

        public Criteria andPrcsDtEqualTo(Date value) {
            addCriterion("PRCS_DT =", value, "prcsDt");
            return (Criteria) this;
        }

        public Criteria andPrcsDtNotEqualTo(Date value) {
            addCriterion("PRCS_DT <>", value, "prcsDt");
            return (Criteria) this;
        }

        public Criteria andPrcsDtGreaterThan(Date value) {
            addCriterion("PRCS_DT >", value, "prcsDt");
            return (Criteria) this;
        }

        public Criteria andPrcsDtGreaterThanOrEqualTo(Date value) {
            addCriterion("PRCS_DT >=", value, "prcsDt");
            return (Criteria) this;
        }

        public Criteria andPrcsDtLessThan(Date value) {
            addCriterion("PRCS_DT <", value, "prcsDt");
            return (Criteria) this;
        }

        public Criteria andPrcsDtLessThanOrEqualTo(Date value) {
            addCriterion("PRCS_DT <=", value, "prcsDt");
            return (Criteria) this;
        }

        public Criteria andPrcsDtIn(List<Date> values) {
            addCriterion("PRCS_DT in", values, "prcsDt");
            return (Criteria) this;
        }

        public Criteria andPrcsDtNotIn(List<Date> values) {
            addCriterion("PRCS_DT not in", values, "prcsDt");
            return (Criteria) this;
        }

        public Criteria andPrcsDtBetween(Date value1, Date value2) {
            addCriterion("PRCS_DT between", value1, value2, "prcsDt");
            return (Criteria) this;
        }

        public Criteria andPrcsDtNotBetween(Date value1, Date value2) {
            addCriterion("PRCS_DT not between", value1, value2, "prcsDt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 09 09:44:34 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SSCF_WORK_MAIN
     *
     * @mbggenerated Wed Nov 09 09:44:34 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}