package org.hf.jsem.entity;

import java.math.BigDecimal;
import java.util.Date;

public class SscfDiffAccounts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.DIFF_ID
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private BigDecimal diffId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.XD_CRT_DT
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private Date xdCrtDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.XD_TRADE_TYPE
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private String xdTradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.XD_TRADE_TYPE_ZH
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private String xdTradeTypeZh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.XD_TRADE_STATUS
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private String xdTradeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.XD_TRADE_STATUS_ZH
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private String xdTradeStatusZh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.APPLY_NO
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.ZF_TRADE_TYPE
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private String zfTradeType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.ZF_TRADE_TYPE_ZH
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private String zfTradeTypeZh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.ZF_TRADE_STATUS
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private String zfTradeStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.ZF_TRADE_STATUS_ZH
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private String zfTradeStatusZh;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.ZF_CRD_DT
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private Date zfCrdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.TRADE_DT
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private Date tradeDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.REMARK
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.FIN_FLAG
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private String finFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.ACCOUNT_OWNER_CD
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private String accountOwnerCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.ACCOUNT_CMP_CD
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private String accountCmpCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_DIFF_ACCOUNTS.SOURCE
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    private String source;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.DIFF_ID
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.DIFF_ID
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public BigDecimal getDiffId() {
        return diffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.DIFF_ID
     *
     * @param diffId the value for SSCF_DIFF_ACCOUNTS.DIFF_ID
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setDiffId(BigDecimal diffId) {
        this.diffId = diffId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.XD_CRT_DT
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.XD_CRT_DT
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public Date getXdCrtDt() {
        return xdCrtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.XD_CRT_DT
     *
     * @param xdCrtDt the value for SSCF_DIFF_ACCOUNTS.XD_CRT_DT
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setXdCrtDt(Date xdCrtDt) {
        this.xdCrtDt = xdCrtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.XD_TRADE_TYPE
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.XD_TRADE_TYPE
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public String getXdTradeType() {
        return xdTradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.XD_TRADE_TYPE
     *
     * @param xdTradeType the value for SSCF_DIFF_ACCOUNTS.XD_TRADE_TYPE
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setXdTradeType(String xdTradeType) {
        this.xdTradeType = xdTradeType == null ? null : xdTradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.XD_TRADE_TYPE_ZH
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.XD_TRADE_TYPE_ZH
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public String getXdTradeTypeZh() {
        return xdTradeTypeZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.XD_TRADE_TYPE_ZH
     *
     * @param xdTradeTypeZh the value for SSCF_DIFF_ACCOUNTS.XD_TRADE_TYPE_ZH
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setXdTradeTypeZh(String xdTradeTypeZh) {
        this.xdTradeTypeZh = xdTradeTypeZh == null ? null : xdTradeTypeZh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.XD_TRADE_STATUS
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.XD_TRADE_STATUS
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public String getXdTradeStatus() {
        return xdTradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.XD_TRADE_STATUS
     *
     * @param xdTradeStatus the value for SSCF_DIFF_ACCOUNTS.XD_TRADE_STATUS
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setXdTradeStatus(String xdTradeStatus) {
        this.xdTradeStatus = xdTradeStatus == null ? null : xdTradeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.XD_TRADE_STATUS_ZH
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.XD_TRADE_STATUS_ZH
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public String getXdTradeStatusZh() {
        return xdTradeStatusZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.XD_TRADE_STATUS_ZH
     *
     * @param xdTradeStatusZh the value for SSCF_DIFF_ACCOUNTS.XD_TRADE_STATUS_ZH
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setXdTradeStatusZh(String xdTradeStatusZh) {
        this.xdTradeStatusZh = xdTradeStatusZh == null ? null : xdTradeStatusZh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.APPLY_NO
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.APPLY_NO
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.APPLY_NO
     *
     * @param applyNo the value for SSCF_DIFF_ACCOUNTS.APPLY_NO
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo == null ? null : applyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.ZF_TRADE_TYPE
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.ZF_TRADE_TYPE
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public String getZfTradeType() {
        return zfTradeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.ZF_TRADE_TYPE
     *
     * @param zfTradeType the value for SSCF_DIFF_ACCOUNTS.ZF_TRADE_TYPE
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setZfTradeType(String zfTradeType) {
        this.zfTradeType = zfTradeType == null ? null : zfTradeType.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.ZF_TRADE_TYPE_ZH
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.ZF_TRADE_TYPE_ZH
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public String getZfTradeTypeZh() {
        return zfTradeTypeZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.ZF_TRADE_TYPE_ZH
     *
     * @param zfTradeTypeZh the value for SSCF_DIFF_ACCOUNTS.ZF_TRADE_TYPE_ZH
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setZfTradeTypeZh(String zfTradeTypeZh) {
        this.zfTradeTypeZh = zfTradeTypeZh == null ? null : zfTradeTypeZh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.ZF_TRADE_STATUS
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.ZF_TRADE_STATUS
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public String getZfTradeStatus() {
        return zfTradeStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.ZF_TRADE_STATUS
     *
     * @param zfTradeStatus the value for SSCF_DIFF_ACCOUNTS.ZF_TRADE_STATUS
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setZfTradeStatus(String zfTradeStatus) {
        this.zfTradeStatus = zfTradeStatus == null ? null : zfTradeStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.ZF_TRADE_STATUS_ZH
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.ZF_TRADE_STATUS_ZH
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public String getZfTradeStatusZh() {
        return zfTradeStatusZh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.ZF_TRADE_STATUS_ZH
     *
     * @param zfTradeStatusZh the value for SSCF_DIFF_ACCOUNTS.ZF_TRADE_STATUS_ZH
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setZfTradeStatusZh(String zfTradeStatusZh) {
        this.zfTradeStatusZh = zfTradeStatusZh == null ? null : zfTradeStatusZh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.ZF_CRD_DT
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.ZF_CRD_DT
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public Date getZfCrdDt() {
        return zfCrdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.ZF_CRD_DT
     *
     * @param zfCrdDt the value for SSCF_DIFF_ACCOUNTS.ZF_CRD_DT
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setZfCrdDt(Date zfCrdDt) {
        this.zfCrdDt = zfCrdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.TRADE_DT
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.TRADE_DT
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public Date getTradeDt() {
        return tradeDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.TRADE_DT
     *
     * @param tradeDt the value for SSCF_DIFF_ACCOUNTS.TRADE_DT
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setTradeDt(Date tradeDt) {
        this.tradeDt = tradeDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.REMARK
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.REMARK
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.REMARK
     *
     * @param remark the value for SSCF_DIFF_ACCOUNTS.REMARK
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.FIN_FLAG
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.FIN_FLAG
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public String getFinFlag() {
        return finFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.FIN_FLAG
     *
     * @param finFlag the value for SSCF_DIFF_ACCOUNTS.FIN_FLAG
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setFinFlag(String finFlag) {
        this.finFlag = finFlag == null ? null : finFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.ACCOUNT_OWNER_CD
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.ACCOUNT_OWNER_CD
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public String getAccountOwnerCd() {
        return accountOwnerCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.ACCOUNT_OWNER_CD
     *
     * @param accountOwnerCd the value for SSCF_DIFF_ACCOUNTS.ACCOUNT_OWNER_CD
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setAccountOwnerCd(String accountOwnerCd) {
        this.accountOwnerCd = accountOwnerCd == null ? null : accountOwnerCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.ACCOUNT_CMP_CD
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.ACCOUNT_CMP_CD
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public String getAccountCmpCd() {
        return accountCmpCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.ACCOUNT_CMP_CD
     *
     * @param accountCmpCd the value for SSCF_DIFF_ACCOUNTS.ACCOUNT_CMP_CD
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setAccountCmpCd(String accountCmpCd) {
        this.accountCmpCd = accountCmpCd == null ? null : accountCmpCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_DIFF_ACCOUNTS.SOURCE
     *
     * @return the value of SSCF_DIFF_ACCOUNTS.SOURCE
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public String getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_DIFF_ACCOUNTS.SOURCE
     *
     * @param source the value for SSCF_DIFF_ACCOUNTS.SOURCE
     *
     * @mbggenerated Fri Nov 04 11:37:37 CST 2016
     */
    public void setSource(String source) {
        this.source = source == null ? null : source.trim();
    }
}