package org.hf.jsem.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class SscfDiffAccountsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public SscfDiffAccountsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andDiffIdIsNull() {
            addCriterion("DIFF_ID is null");
            return (Criteria) this;
        }

        public Criteria andDiffIdIsNotNull() {
            addCriterion("DIFF_ID is not null");
            return (Criteria) this;
        }

        public Criteria andDiffIdEqualTo(BigDecimal value) {
            addCriterion("DIFF_ID =", value, "diffId");
            return (Criteria) this;
        }

        public Criteria andDiffIdNotEqualTo(BigDecimal value) {
            addCriterion("DIFF_ID <>", value, "diffId");
            return (Criteria) this;
        }

        public Criteria andDiffIdGreaterThan(BigDecimal value) {
            addCriterion("DIFF_ID >", value, "diffId");
            return (Criteria) this;
        }

        public Criteria andDiffIdGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("DIFF_ID >=", value, "diffId");
            return (Criteria) this;
        }

        public Criteria andDiffIdLessThan(BigDecimal value) {
            addCriterion("DIFF_ID <", value, "diffId");
            return (Criteria) this;
        }

        public Criteria andDiffIdLessThanOrEqualTo(BigDecimal value) {
            addCriterion("DIFF_ID <=", value, "diffId");
            return (Criteria) this;
        }

        public Criteria andDiffIdIn(List<BigDecimal> values) {
            addCriterion("DIFF_ID in", values, "diffId");
            return (Criteria) this;
        }

        public Criteria andDiffIdNotIn(List<BigDecimal> values) {
            addCriterion("DIFF_ID not in", values, "diffId");
            return (Criteria) this;
        }

        public Criteria andDiffIdBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DIFF_ID between", value1, value2, "diffId");
            return (Criteria) this;
        }

        public Criteria andDiffIdNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("DIFF_ID not between", value1, value2, "diffId");
            return (Criteria) this;
        }

        public Criteria andXdCrtDtIsNull() {
            addCriterion("XD_CRT_DT is null");
            return (Criteria) this;
        }

        public Criteria andXdCrtDtIsNotNull() {
            addCriterion("XD_CRT_DT is not null");
            return (Criteria) this;
        }

        public Criteria andXdCrtDtEqualTo(Date value) {
            addCriterion("XD_CRT_DT =", value, "xdCrtDt");
            return (Criteria) this;
        }

        public Criteria andXdCrtDtNotEqualTo(Date value) {
            addCriterion("XD_CRT_DT <>", value, "xdCrtDt");
            return (Criteria) this;
        }

        public Criteria andXdCrtDtGreaterThan(Date value) {
            addCriterion("XD_CRT_DT >", value, "xdCrtDt");
            return (Criteria) this;
        }

        public Criteria andXdCrtDtGreaterThanOrEqualTo(Date value) {
            addCriterion("XD_CRT_DT >=", value, "xdCrtDt");
            return (Criteria) this;
        }

        public Criteria andXdCrtDtLessThan(Date value) {
            addCriterion("XD_CRT_DT <", value, "xdCrtDt");
            return (Criteria) this;
        }

        public Criteria andXdCrtDtLessThanOrEqualTo(Date value) {
            addCriterion("XD_CRT_DT <=", value, "xdCrtDt");
            return (Criteria) this;
        }

        public Criteria andXdCrtDtIn(List<Date> values) {
            addCriterion("XD_CRT_DT in", values, "xdCrtDt");
            return (Criteria) this;
        }

        public Criteria andXdCrtDtNotIn(List<Date> values) {
            addCriterion("XD_CRT_DT not in", values, "xdCrtDt");
            return (Criteria) this;
        }

        public Criteria andXdCrtDtBetween(Date value1, Date value2) {
            addCriterion("XD_CRT_DT between", value1, value2, "xdCrtDt");
            return (Criteria) this;
        }

        public Criteria andXdCrtDtNotBetween(Date value1, Date value2) {
            addCriterion("XD_CRT_DT not between", value1, value2, "xdCrtDt");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeIsNull() {
            addCriterion("XD_TRADE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeIsNotNull() {
            addCriterion("XD_TRADE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeEqualTo(String value) {
            addCriterion("XD_TRADE_TYPE =", value, "xdTradeType");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeNotEqualTo(String value) {
            addCriterion("XD_TRADE_TYPE <>", value, "xdTradeType");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeGreaterThan(String value) {
            addCriterion("XD_TRADE_TYPE >", value, "xdTradeType");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("XD_TRADE_TYPE >=", value, "xdTradeType");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeLessThan(String value) {
            addCriterion("XD_TRADE_TYPE <", value, "xdTradeType");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeLessThanOrEqualTo(String value) {
            addCriterion("XD_TRADE_TYPE <=", value, "xdTradeType");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeLike(String value) {
            addCriterion("XD_TRADE_TYPE like", value, "xdTradeType");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeNotLike(String value) {
            addCriterion("XD_TRADE_TYPE not like", value, "xdTradeType");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeIn(List<String> values) {
            addCriterion("XD_TRADE_TYPE in", values, "xdTradeType");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeNotIn(List<String> values) {
            addCriterion("XD_TRADE_TYPE not in", values, "xdTradeType");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeBetween(String value1, String value2) {
            addCriterion("XD_TRADE_TYPE between", value1, value2, "xdTradeType");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeNotBetween(String value1, String value2) {
            addCriterion("XD_TRADE_TYPE not between", value1, value2, "xdTradeType");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeZhIsNull() {
            addCriterion("XD_TRADE_TYPE_ZH is null");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeZhIsNotNull() {
            addCriterion("XD_TRADE_TYPE_ZH is not null");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeZhEqualTo(String value) {
            addCriterion("XD_TRADE_TYPE_ZH =", value, "xdTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeZhNotEqualTo(String value) {
            addCriterion("XD_TRADE_TYPE_ZH <>", value, "xdTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeZhGreaterThan(String value) {
            addCriterion("XD_TRADE_TYPE_ZH >", value, "xdTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeZhGreaterThanOrEqualTo(String value) {
            addCriterion("XD_TRADE_TYPE_ZH >=", value, "xdTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeZhLessThan(String value) {
            addCriterion("XD_TRADE_TYPE_ZH <", value, "xdTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeZhLessThanOrEqualTo(String value) {
            addCriterion("XD_TRADE_TYPE_ZH <=", value, "xdTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeZhLike(String value) {
            addCriterion("XD_TRADE_TYPE_ZH like", value, "xdTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeZhNotLike(String value) {
            addCriterion("XD_TRADE_TYPE_ZH not like", value, "xdTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeZhIn(List<String> values) {
            addCriterion("XD_TRADE_TYPE_ZH in", values, "xdTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeZhNotIn(List<String> values) {
            addCriterion("XD_TRADE_TYPE_ZH not in", values, "xdTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeZhBetween(String value1, String value2) {
            addCriterion("XD_TRADE_TYPE_ZH between", value1, value2, "xdTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeTypeZhNotBetween(String value1, String value2) {
            addCriterion("XD_TRADE_TYPE_ZH not between", value1, value2, "xdTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusIsNull() {
            addCriterion("XD_TRADE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusIsNotNull() {
            addCriterion("XD_TRADE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusEqualTo(String value) {
            addCriterion("XD_TRADE_STATUS =", value, "xdTradeStatus");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusNotEqualTo(String value) {
            addCriterion("XD_TRADE_STATUS <>", value, "xdTradeStatus");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusGreaterThan(String value) {
            addCriterion("XD_TRADE_STATUS >", value, "xdTradeStatus");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusGreaterThanOrEqualTo(String value) {
            addCriterion("XD_TRADE_STATUS >=", value, "xdTradeStatus");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusLessThan(String value) {
            addCriterion("XD_TRADE_STATUS <", value, "xdTradeStatus");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusLessThanOrEqualTo(String value) {
            addCriterion("XD_TRADE_STATUS <=", value, "xdTradeStatus");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusLike(String value) {
            addCriterion("XD_TRADE_STATUS like", value, "xdTradeStatus");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusNotLike(String value) {
            addCriterion("XD_TRADE_STATUS not like", value, "xdTradeStatus");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusIn(List<String> values) {
            addCriterion("XD_TRADE_STATUS in", values, "xdTradeStatus");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusNotIn(List<String> values) {
            addCriterion("XD_TRADE_STATUS not in", values, "xdTradeStatus");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusBetween(String value1, String value2) {
            addCriterion("XD_TRADE_STATUS between", value1, value2, "xdTradeStatus");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusNotBetween(String value1, String value2) {
            addCriterion("XD_TRADE_STATUS not between", value1, value2, "xdTradeStatus");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusZhIsNull() {
            addCriterion("XD_TRADE_STATUS_ZH is null");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusZhIsNotNull() {
            addCriterion("XD_TRADE_STATUS_ZH is not null");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusZhEqualTo(String value) {
            addCriterion("XD_TRADE_STATUS_ZH =", value, "xdTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusZhNotEqualTo(String value) {
            addCriterion("XD_TRADE_STATUS_ZH <>", value, "xdTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusZhGreaterThan(String value) {
            addCriterion("XD_TRADE_STATUS_ZH >", value, "xdTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusZhGreaterThanOrEqualTo(String value) {
            addCriterion("XD_TRADE_STATUS_ZH >=", value, "xdTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusZhLessThan(String value) {
            addCriterion("XD_TRADE_STATUS_ZH <", value, "xdTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusZhLessThanOrEqualTo(String value) {
            addCriterion("XD_TRADE_STATUS_ZH <=", value, "xdTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusZhLike(String value) {
            addCriterion("XD_TRADE_STATUS_ZH like", value, "xdTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusZhNotLike(String value) {
            addCriterion("XD_TRADE_STATUS_ZH not like", value, "xdTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusZhIn(List<String> values) {
            addCriterion("XD_TRADE_STATUS_ZH in", values, "xdTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusZhNotIn(List<String> values) {
            addCriterion("XD_TRADE_STATUS_ZH not in", values, "xdTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusZhBetween(String value1, String value2) {
            addCriterion("XD_TRADE_STATUS_ZH between", value1, value2, "xdTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andXdTradeStatusZhNotBetween(String value1, String value2) {
            addCriterion("XD_TRADE_STATUS_ZH not between", value1, value2, "xdTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andApplyNoIsNull() {
            addCriterion("APPLY_NO is null");
            return (Criteria) this;
        }

        public Criteria andApplyNoIsNotNull() {
            addCriterion("APPLY_NO is not null");
            return (Criteria) this;
        }

        public Criteria andApplyNoEqualTo(String value) {
            addCriterion("APPLY_NO =", value, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoNotEqualTo(String value) {
            addCriterion("APPLY_NO <>", value, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoGreaterThan(String value) {
            addCriterion("APPLY_NO >", value, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoGreaterThanOrEqualTo(String value) {
            addCriterion("APPLY_NO >=", value, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoLessThan(String value) {
            addCriterion("APPLY_NO <", value, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoLessThanOrEqualTo(String value) {
            addCriterion("APPLY_NO <=", value, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoLike(String value) {
            addCriterion("APPLY_NO like", value, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoNotLike(String value) {
            addCriterion("APPLY_NO not like", value, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoIn(List<String> values) {
            addCriterion("APPLY_NO in", values, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoNotIn(List<String> values) {
            addCriterion("APPLY_NO not in", values, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoBetween(String value1, String value2) {
            addCriterion("APPLY_NO between", value1, value2, "applyNo");
            return (Criteria) this;
        }

        public Criteria andApplyNoNotBetween(String value1, String value2) {
            addCriterion("APPLY_NO not between", value1, value2, "applyNo");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeIsNull() {
            addCriterion("ZF_TRADE_TYPE is null");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeIsNotNull() {
            addCriterion("ZF_TRADE_TYPE is not null");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeEqualTo(String value) {
            addCriterion("ZF_TRADE_TYPE =", value, "zfTradeType");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeNotEqualTo(String value) {
            addCriterion("ZF_TRADE_TYPE <>", value, "zfTradeType");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeGreaterThan(String value) {
            addCriterion("ZF_TRADE_TYPE >", value, "zfTradeType");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeGreaterThanOrEqualTo(String value) {
            addCriterion("ZF_TRADE_TYPE >=", value, "zfTradeType");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeLessThan(String value) {
            addCriterion("ZF_TRADE_TYPE <", value, "zfTradeType");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeLessThanOrEqualTo(String value) {
            addCriterion("ZF_TRADE_TYPE <=", value, "zfTradeType");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeLike(String value) {
            addCriterion("ZF_TRADE_TYPE like", value, "zfTradeType");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeNotLike(String value) {
            addCriterion("ZF_TRADE_TYPE not like", value, "zfTradeType");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeIn(List<String> values) {
            addCriterion("ZF_TRADE_TYPE in", values, "zfTradeType");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeNotIn(List<String> values) {
            addCriterion("ZF_TRADE_TYPE not in", values, "zfTradeType");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeBetween(String value1, String value2) {
            addCriterion("ZF_TRADE_TYPE between", value1, value2, "zfTradeType");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeNotBetween(String value1, String value2) {
            addCriterion("ZF_TRADE_TYPE not between", value1, value2, "zfTradeType");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeZhIsNull() {
            addCriterion("ZF_TRADE_TYPE_ZH is null");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeZhIsNotNull() {
            addCriterion("ZF_TRADE_TYPE_ZH is not null");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeZhEqualTo(String value) {
            addCriterion("ZF_TRADE_TYPE_ZH =", value, "zfTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeZhNotEqualTo(String value) {
            addCriterion("ZF_TRADE_TYPE_ZH <>", value, "zfTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeZhGreaterThan(String value) {
            addCriterion("ZF_TRADE_TYPE_ZH >", value, "zfTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeZhGreaterThanOrEqualTo(String value) {
            addCriterion("ZF_TRADE_TYPE_ZH >=", value, "zfTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeZhLessThan(String value) {
            addCriterion("ZF_TRADE_TYPE_ZH <", value, "zfTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeZhLessThanOrEqualTo(String value) {
            addCriterion("ZF_TRADE_TYPE_ZH <=", value, "zfTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeZhLike(String value) {
            addCriterion("ZF_TRADE_TYPE_ZH like", value, "zfTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeZhNotLike(String value) {
            addCriterion("ZF_TRADE_TYPE_ZH not like", value, "zfTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeZhIn(List<String> values) {
            addCriterion("ZF_TRADE_TYPE_ZH in", values, "zfTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeZhNotIn(List<String> values) {
            addCriterion("ZF_TRADE_TYPE_ZH not in", values, "zfTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeZhBetween(String value1, String value2) {
            addCriterion("ZF_TRADE_TYPE_ZH between", value1, value2, "zfTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeTypeZhNotBetween(String value1, String value2) {
            addCriterion("ZF_TRADE_TYPE_ZH not between", value1, value2, "zfTradeTypeZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusIsNull() {
            addCriterion("ZF_TRADE_STATUS is null");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusIsNotNull() {
            addCriterion("ZF_TRADE_STATUS is not null");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusEqualTo(String value) {
            addCriterion("ZF_TRADE_STATUS =", value, "zfTradeStatus");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusNotEqualTo(String value) {
            addCriterion("ZF_TRADE_STATUS <>", value, "zfTradeStatus");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusGreaterThan(String value) {
            addCriterion("ZF_TRADE_STATUS >", value, "zfTradeStatus");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusGreaterThanOrEqualTo(String value) {
            addCriterion("ZF_TRADE_STATUS >=", value, "zfTradeStatus");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusLessThan(String value) {
            addCriterion("ZF_TRADE_STATUS <", value, "zfTradeStatus");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusLessThanOrEqualTo(String value) {
            addCriterion("ZF_TRADE_STATUS <=", value, "zfTradeStatus");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusLike(String value) {
            addCriterion("ZF_TRADE_STATUS like", value, "zfTradeStatus");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusNotLike(String value) {
            addCriterion("ZF_TRADE_STATUS not like", value, "zfTradeStatus");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusIn(List<String> values) {
            addCriterion("ZF_TRADE_STATUS in", values, "zfTradeStatus");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusNotIn(List<String> values) {
            addCriterion("ZF_TRADE_STATUS not in", values, "zfTradeStatus");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusBetween(String value1, String value2) {
            addCriterion("ZF_TRADE_STATUS between", value1, value2, "zfTradeStatus");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusNotBetween(String value1, String value2) {
            addCriterion("ZF_TRADE_STATUS not between", value1, value2, "zfTradeStatus");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusZhIsNull() {
            addCriterion("ZF_TRADE_STATUS_ZH is null");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusZhIsNotNull() {
            addCriterion("ZF_TRADE_STATUS_ZH is not null");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusZhEqualTo(String value) {
            addCriterion("ZF_TRADE_STATUS_ZH =", value, "zfTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusZhNotEqualTo(String value) {
            addCriterion("ZF_TRADE_STATUS_ZH <>", value, "zfTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusZhGreaterThan(String value) {
            addCriterion("ZF_TRADE_STATUS_ZH >", value, "zfTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusZhGreaterThanOrEqualTo(String value) {
            addCriterion("ZF_TRADE_STATUS_ZH >=", value, "zfTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusZhLessThan(String value) {
            addCriterion("ZF_TRADE_STATUS_ZH <", value, "zfTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusZhLessThanOrEqualTo(String value) {
            addCriterion("ZF_TRADE_STATUS_ZH <=", value, "zfTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusZhLike(String value) {
            addCriterion("ZF_TRADE_STATUS_ZH like", value, "zfTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusZhNotLike(String value) {
            addCriterion("ZF_TRADE_STATUS_ZH not like", value, "zfTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusZhIn(List<String> values) {
            addCriterion("ZF_TRADE_STATUS_ZH in", values, "zfTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusZhNotIn(List<String> values) {
            addCriterion("ZF_TRADE_STATUS_ZH not in", values, "zfTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusZhBetween(String value1, String value2) {
            addCriterion("ZF_TRADE_STATUS_ZH between", value1, value2, "zfTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andZfTradeStatusZhNotBetween(String value1, String value2) {
            addCriterion("ZF_TRADE_STATUS_ZH not between", value1, value2, "zfTradeStatusZh");
            return (Criteria) this;
        }

        public Criteria andZfCrdDtIsNull() {
            addCriterion("ZF_CRD_DT is null");
            return (Criteria) this;
        }

        public Criteria andZfCrdDtIsNotNull() {
            addCriterion("ZF_CRD_DT is not null");
            return (Criteria) this;
        }

        public Criteria andZfCrdDtEqualTo(Date value) {
            addCriterion("ZF_CRD_DT =", value, "zfCrdDt");
            return (Criteria) this;
        }

        public Criteria andZfCrdDtNotEqualTo(Date value) {
            addCriterion("ZF_CRD_DT <>", value, "zfCrdDt");
            return (Criteria) this;
        }

        public Criteria andZfCrdDtGreaterThan(Date value) {
            addCriterion("ZF_CRD_DT >", value, "zfCrdDt");
            return (Criteria) this;
        }

        public Criteria andZfCrdDtGreaterThanOrEqualTo(Date value) {
            addCriterion("ZF_CRD_DT >=", value, "zfCrdDt");
            return (Criteria) this;
        }

        public Criteria andZfCrdDtLessThan(Date value) {
            addCriterion("ZF_CRD_DT <", value, "zfCrdDt");
            return (Criteria) this;
        }

        public Criteria andZfCrdDtLessThanOrEqualTo(Date value) {
            addCriterion("ZF_CRD_DT <=", value, "zfCrdDt");
            return (Criteria) this;
        }

        public Criteria andZfCrdDtIn(List<Date> values) {
            addCriterion("ZF_CRD_DT in", values, "zfCrdDt");
            return (Criteria) this;
        }

        public Criteria andZfCrdDtNotIn(List<Date> values) {
            addCriterion("ZF_CRD_DT not in", values, "zfCrdDt");
            return (Criteria) this;
        }

        public Criteria andZfCrdDtBetween(Date value1, Date value2) {
            addCriterion("ZF_CRD_DT between", value1, value2, "zfCrdDt");
            return (Criteria) this;
        }

        public Criteria andZfCrdDtNotBetween(Date value1, Date value2) {
            addCriterion("ZF_CRD_DT not between", value1, value2, "zfCrdDt");
            return (Criteria) this;
        }

        public Criteria andTradeDtIsNull() {
            addCriterion("TRADE_DT is null");
            return (Criteria) this;
        }

        public Criteria andTradeDtIsNotNull() {
            addCriterion("TRADE_DT is not null");
            return (Criteria) this;
        }

        public Criteria andTradeDtEqualTo(Date value) {
            addCriterion("TRADE_DT =", value, "tradeDt");
            return (Criteria) this;
        }

        public Criteria andTradeDtNotEqualTo(Date value) {
            addCriterion("TRADE_DT <>", value, "tradeDt");
            return (Criteria) this;
        }

        public Criteria andTradeDtGreaterThan(Date value) {
            addCriterion("TRADE_DT >", value, "tradeDt");
            return (Criteria) this;
        }

        public Criteria andTradeDtGreaterThanOrEqualTo(Date value) {
            addCriterion("TRADE_DT >=", value, "tradeDt");
            return (Criteria) this;
        }

        public Criteria andTradeDtLessThan(Date value) {
            addCriterion("TRADE_DT <", value, "tradeDt");
            return (Criteria) this;
        }

        public Criteria andTradeDtLessThanOrEqualTo(Date value) {
            addCriterion("TRADE_DT <=", value, "tradeDt");
            return (Criteria) this;
        }

        public Criteria andTradeDtIn(List<Date> values) {
            addCriterion("TRADE_DT in", values, "tradeDt");
            return (Criteria) this;
        }

        public Criteria andTradeDtNotIn(List<Date> values) {
            addCriterion("TRADE_DT not in", values, "tradeDt");
            return (Criteria) this;
        }

        public Criteria andTradeDtBetween(Date value1, Date value2) {
            addCriterion("TRADE_DT between", value1, value2, "tradeDt");
            return (Criteria) this;
        }

        public Criteria andTradeDtNotBetween(Date value1, Date value2) {
            addCriterion("TRADE_DT not between", value1, value2, "tradeDt");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNull() {
            addCriterion("REMARK is null");
            return (Criteria) this;
        }

        public Criteria andRemarkIsNotNull() {
            addCriterion("REMARK is not null");
            return (Criteria) this;
        }

        public Criteria andRemarkEqualTo(String value) {
            addCriterion("REMARK =", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotEqualTo(String value) {
            addCriterion("REMARK <>", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThan(String value) {
            addCriterion("REMARK >", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkGreaterThanOrEqualTo(String value) {
            addCriterion("REMARK >=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThan(String value) {
            addCriterion("REMARK <", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLessThanOrEqualTo(String value) {
            addCriterion("REMARK <=", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkLike(String value) {
            addCriterion("REMARK like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotLike(String value) {
            addCriterion("REMARK not like", value, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkIn(List<String> values) {
            addCriterion("REMARK in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotIn(List<String> values) {
            addCriterion("REMARK not in", values, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkBetween(String value1, String value2) {
            addCriterion("REMARK between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andRemarkNotBetween(String value1, String value2) {
            addCriterion("REMARK not between", value1, value2, "remark");
            return (Criteria) this;
        }

        public Criteria andFinFlagIsNull() {
            addCriterion("FIN_FLAG is null");
            return (Criteria) this;
        }

        public Criteria andFinFlagIsNotNull() {
            addCriterion("FIN_FLAG is not null");
            return (Criteria) this;
        }

        public Criteria andFinFlagEqualTo(String value) {
            addCriterion("FIN_FLAG =", value, "finFlag");
            return (Criteria) this;
        }

        public Criteria andFinFlagNotEqualTo(String value) {
            addCriterion("FIN_FLAG <>", value, "finFlag");
            return (Criteria) this;
        }

        public Criteria andFinFlagGreaterThan(String value) {
            addCriterion("FIN_FLAG >", value, "finFlag");
            return (Criteria) this;
        }

        public Criteria andFinFlagGreaterThanOrEqualTo(String value) {
            addCriterion("FIN_FLAG >=", value, "finFlag");
            return (Criteria) this;
        }

        public Criteria andFinFlagLessThan(String value) {
            addCriterion("FIN_FLAG <", value, "finFlag");
            return (Criteria) this;
        }

        public Criteria andFinFlagLessThanOrEqualTo(String value) {
            addCriterion("FIN_FLAG <=", value, "finFlag");
            return (Criteria) this;
        }

        public Criteria andFinFlagLike(String value) {
            addCriterion("FIN_FLAG like", value, "finFlag");
            return (Criteria) this;
        }

        public Criteria andFinFlagNotLike(String value) {
            addCriterion("FIN_FLAG not like", value, "finFlag");
            return (Criteria) this;
        }

        public Criteria andFinFlagIn(List<String> values) {
            addCriterion("FIN_FLAG in", values, "finFlag");
            return (Criteria) this;
        }

        public Criteria andFinFlagNotIn(List<String> values) {
            addCriterion("FIN_FLAG not in", values, "finFlag");
            return (Criteria) this;
        }

        public Criteria andFinFlagBetween(String value1, String value2) {
            addCriterion("FIN_FLAG between", value1, value2, "finFlag");
            return (Criteria) this;
        }

        public Criteria andFinFlagNotBetween(String value1, String value2) {
            addCriterion("FIN_FLAG not between", value1, value2, "finFlag");
            return (Criteria) this;
        }

        public Criteria andAccountOwnerCdIsNull() {
            addCriterion("ACCOUNT_OWNER_CD is null");
            return (Criteria) this;
        }

        public Criteria andAccountOwnerCdIsNotNull() {
            addCriterion("ACCOUNT_OWNER_CD is not null");
            return (Criteria) this;
        }

        public Criteria andAccountOwnerCdEqualTo(String value) {
            addCriterion("ACCOUNT_OWNER_CD =", value, "accountOwnerCd");
            return (Criteria) this;
        }

        public Criteria andAccountOwnerCdNotEqualTo(String value) {
            addCriterion("ACCOUNT_OWNER_CD <>", value, "accountOwnerCd");
            return (Criteria) this;
        }

        public Criteria andAccountOwnerCdGreaterThan(String value) {
            addCriterion("ACCOUNT_OWNER_CD >", value, "accountOwnerCd");
            return (Criteria) this;
        }

        public Criteria andAccountOwnerCdGreaterThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_OWNER_CD >=", value, "accountOwnerCd");
            return (Criteria) this;
        }

        public Criteria andAccountOwnerCdLessThan(String value) {
            addCriterion("ACCOUNT_OWNER_CD <", value, "accountOwnerCd");
            return (Criteria) this;
        }

        public Criteria andAccountOwnerCdLessThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_OWNER_CD <=", value, "accountOwnerCd");
            return (Criteria) this;
        }

        public Criteria andAccountOwnerCdLike(String value) {
            addCriterion("ACCOUNT_OWNER_CD like", value, "accountOwnerCd");
            return (Criteria) this;
        }

        public Criteria andAccountOwnerCdNotLike(String value) {
            addCriterion("ACCOUNT_OWNER_CD not like", value, "accountOwnerCd");
            return (Criteria) this;
        }

        public Criteria andAccountOwnerCdIn(List<String> values) {
            addCriterion("ACCOUNT_OWNER_CD in", values, "accountOwnerCd");
            return (Criteria) this;
        }

        public Criteria andAccountOwnerCdNotIn(List<String> values) {
            addCriterion("ACCOUNT_OWNER_CD not in", values, "accountOwnerCd");
            return (Criteria) this;
        }

        public Criteria andAccountOwnerCdBetween(String value1, String value2) {
            addCriterion("ACCOUNT_OWNER_CD between", value1, value2, "accountOwnerCd");
            return (Criteria) this;
        }

        public Criteria andAccountOwnerCdNotBetween(String value1, String value2) {
            addCriterion("ACCOUNT_OWNER_CD not between", value1, value2, "accountOwnerCd");
            return (Criteria) this;
        }

        public Criteria andAccountCmpCdIsNull() {
            addCriterion("ACCOUNT_CMP_CD is null");
            return (Criteria) this;
        }

        public Criteria andAccountCmpCdIsNotNull() {
            addCriterion("ACCOUNT_CMP_CD is not null");
            return (Criteria) this;
        }

        public Criteria andAccountCmpCdEqualTo(String value) {
            addCriterion("ACCOUNT_CMP_CD =", value, "accountCmpCd");
            return (Criteria) this;
        }

        public Criteria andAccountCmpCdNotEqualTo(String value) {
            addCriterion("ACCOUNT_CMP_CD <>", value, "accountCmpCd");
            return (Criteria) this;
        }

        public Criteria andAccountCmpCdGreaterThan(String value) {
            addCriterion("ACCOUNT_CMP_CD >", value, "accountCmpCd");
            return (Criteria) this;
        }

        public Criteria andAccountCmpCdGreaterThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_CMP_CD >=", value, "accountCmpCd");
            return (Criteria) this;
        }

        public Criteria andAccountCmpCdLessThan(String value) {
            addCriterion("ACCOUNT_CMP_CD <", value, "accountCmpCd");
            return (Criteria) this;
        }

        public Criteria andAccountCmpCdLessThanOrEqualTo(String value) {
            addCriterion("ACCOUNT_CMP_CD <=", value, "accountCmpCd");
            return (Criteria) this;
        }

        public Criteria andAccountCmpCdLike(String value) {
            addCriterion("ACCOUNT_CMP_CD like", value, "accountCmpCd");
            return (Criteria) this;
        }

        public Criteria andAccountCmpCdNotLike(String value) {
            addCriterion("ACCOUNT_CMP_CD not like", value, "accountCmpCd");
            return (Criteria) this;
        }

        public Criteria andAccountCmpCdIn(List<String> values) {
            addCriterion("ACCOUNT_CMP_CD in", values, "accountCmpCd");
            return (Criteria) this;
        }

        public Criteria andAccountCmpCdNotIn(List<String> values) {
            addCriterion("ACCOUNT_CMP_CD not in", values, "accountCmpCd");
            return (Criteria) this;
        }

        public Criteria andAccountCmpCdBetween(String value1, String value2) {
            addCriterion("ACCOUNT_CMP_CD between", value1, value2, "accountCmpCd");
            return (Criteria) this;
        }

        public Criteria andAccountCmpCdNotBetween(String value1, String value2) {
            addCriterion("ACCOUNT_CMP_CD not between", value1, value2, "accountCmpCd");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("SOURCE is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("SOURCE is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(String value) {
            addCriterion("SOURCE =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(String value) {
            addCriterion("SOURCE <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(String value) {
            addCriterion("SOURCE >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(String value) {
            addCriterion("SOURCE >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(String value) {
            addCriterion("SOURCE <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(String value) {
            addCriterion("SOURCE <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLike(String value) {
            addCriterion("SOURCE like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotLike(String value) {
            addCriterion("SOURCE not like", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<String> values) {
            addCriterion("SOURCE in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<String> values) {
            addCriterion("SOURCE not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(String value1, String value2) {
            addCriterion("SOURCE between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(String value1, String value2) {
            addCriterion("SOURCE not between", value1, value2, "source");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated do_not_delete_during_merge Wed Nov 02 17:54:01 CST 2016
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table SSCF_DIFF_ACCOUNTS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value) {
            super();
            this.condition = condition;
            this.value = value;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.betweenValue = true;
        }
    }
}