package org.hf.jsem.entity;

import java.util.Date;

public class SscfWorkMain {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_WORK_MAIN.APPLY_NO
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    private String applyNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_WORK_MAIN.STATUS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_WORK_MAIN.LN_CAT
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    private String lnCat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_WORK_MAIN.PRCS_DT
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    private Date prcsDt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_WORK_MAIN.APPLY_NO
     *
     * @return the value of SSCF_WORK_MAIN.APPLY_NO
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public String getApplyNo() {
        return applyNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_WORK_MAIN.APPLY_NO
     *
     * @param applyNo the value for SSCF_WORK_MAIN.APPLY_NO
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public void setApplyNo(String applyNo) {
        this.applyNo = applyNo == null ? null : applyNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_WORK_MAIN.STATUS
     *
     * @return the value of SSCF_WORK_MAIN.STATUS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_WORK_MAIN.STATUS
     *
     * @param status the value for SSCF_WORK_MAIN.STATUS
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_WORK_MAIN.LN_CAT
     *
     * @return the value of SSCF_WORK_MAIN.LN_CAT
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public String getLnCat() {
        return lnCat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_WORK_MAIN.LN_CAT
     *
     * @param lnCat the value for SSCF_WORK_MAIN.LN_CAT
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public void setLnCat(String lnCat) {
        this.lnCat = lnCat == null ? null : lnCat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_WORK_MAIN.PRCS_DT
     *
     * @return the value of SSCF_WORK_MAIN.PRCS_DT
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public Date getPrcsDt() {
        return prcsDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_WORK_MAIN.PRCS_DT
     *
     * @param prcsDt the value for SSCF_WORK_MAIN.PRCS_DT
     *
     * @mbggenerated Wed Nov 02 17:54:01 CST 2016
     */
    public void setPrcsDt(Date prcsDt) {
        this.prcsDt = prcsDt;
    }
}