package org.hf.jsem.entity;

import java.util.Date;

public class SscfChannel {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.CHANNEL_ID
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private String channelId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.CHANNEL_NAME
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private String channelName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.SEQ_NO
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private Short seqNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.CHANNEL_BRCH_CD
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private String channelBrchCd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.CHANNEL_ACCOUNT_NO
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private String channelAccountNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.LIQUID_TY
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private String liquidTy;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.STATUS
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private String status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.REMARK
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.CRT_USR
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private String crtUsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.CRT_DT
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private Date crtDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.LAST_UPD_USR
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private String lastUpdUsr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.LAST_UPD_DT
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private Date lastUpdDt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.REPAY_ACCT_NO
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private String repayAcctNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.CUST_NO
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private String custNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.BATCH_FLAG
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private String batchFlag;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.BATCH_ACCT
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private String batchAcct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column SSCF_CHANNEL.CHANNEL_OWER
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    private String channelOwer;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.CHANNEL_ID
     *
     * @return the value of SSCF_CHANNEL.CHANNEL_ID
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public String getChannelId() {
        return channelId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.CHANNEL_ID
     *
     * @param channelId the value for SSCF_CHANNEL.CHANNEL_ID
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setChannelId(String channelId) {
        this.channelId = channelId == null ? null : channelId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.CHANNEL_NAME
     *
     * @return the value of SSCF_CHANNEL.CHANNEL_NAME
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public String getChannelName() {
        return channelName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.CHANNEL_NAME
     *
     * @param channelName the value for SSCF_CHANNEL.CHANNEL_NAME
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setChannelName(String channelName) {
        this.channelName = channelName == null ? null : channelName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.SEQ_NO
     *
     * @return the value of SSCF_CHANNEL.SEQ_NO
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public Short getSeqNo() {
        return seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.SEQ_NO
     *
     * @param seqNo the value for SSCF_CHANNEL.SEQ_NO
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setSeqNo(Short seqNo) {
        this.seqNo = seqNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.CHANNEL_BRCH_CD
     *
     * @return the value of SSCF_CHANNEL.CHANNEL_BRCH_CD
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public String getChannelBrchCd() {
        return channelBrchCd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.CHANNEL_BRCH_CD
     *
     * @param channelBrchCd the value for SSCF_CHANNEL.CHANNEL_BRCH_CD
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setChannelBrchCd(String channelBrchCd) {
        this.channelBrchCd = channelBrchCd == null ? null : channelBrchCd.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.CHANNEL_ACCOUNT_NO
     *
     * @return the value of SSCF_CHANNEL.CHANNEL_ACCOUNT_NO
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public String getChannelAccountNo() {
        return channelAccountNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.CHANNEL_ACCOUNT_NO
     *
     * @param channelAccountNo the value for SSCF_CHANNEL.CHANNEL_ACCOUNT_NO
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setChannelAccountNo(String channelAccountNo) {
        this.channelAccountNo = channelAccountNo == null ? null : channelAccountNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.LIQUID_TY
     *
     * @return the value of SSCF_CHANNEL.LIQUID_TY
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public String getLiquidTy() {
        return liquidTy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.LIQUID_TY
     *
     * @param liquidTy the value for SSCF_CHANNEL.LIQUID_TY
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setLiquidTy(String liquidTy) {
        this.liquidTy = liquidTy == null ? null : liquidTy.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.STATUS
     *
     * @return the value of SSCF_CHANNEL.STATUS
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.STATUS
     *
     * @param status the value for SSCF_CHANNEL.STATUS
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.REMARK
     *
     * @return the value of SSCF_CHANNEL.REMARK
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.REMARK
     *
     * @param remark the value for SSCF_CHANNEL.REMARK
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.CRT_USR
     *
     * @return the value of SSCF_CHANNEL.CRT_USR
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public String getCrtUsr() {
        return crtUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.CRT_USR
     *
     * @param crtUsr the value for SSCF_CHANNEL.CRT_USR
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setCrtUsr(String crtUsr) {
        this.crtUsr = crtUsr == null ? null : crtUsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.CRT_DT
     *
     * @return the value of SSCF_CHANNEL.CRT_DT
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public Date getCrtDt() {
        return crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.CRT_DT
     *
     * @param crtDt the value for SSCF_CHANNEL.CRT_DT
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setCrtDt(Date crtDt) {
        this.crtDt = crtDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.LAST_UPD_USR
     *
     * @return the value of SSCF_CHANNEL.LAST_UPD_USR
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public String getLastUpdUsr() {
        return lastUpdUsr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.LAST_UPD_USR
     *
     * @param lastUpdUsr the value for SSCF_CHANNEL.LAST_UPD_USR
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setLastUpdUsr(String lastUpdUsr) {
        this.lastUpdUsr = lastUpdUsr == null ? null : lastUpdUsr.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.LAST_UPD_DT
     *
     * @return the value of SSCF_CHANNEL.LAST_UPD_DT
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public Date getLastUpdDt() {
        return lastUpdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.LAST_UPD_DT
     *
     * @param lastUpdDt the value for SSCF_CHANNEL.LAST_UPD_DT
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setLastUpdDt(Date lastUpdDt) {
        this.lastUpdDt = lastUpdDt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.REPAY_ACCT_NO
     *
     * @return the value of SSCF_CHANNEL.REPAY_ACCT_NO
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public String getRepayAcctNo() {
        return repayAcctNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.REPAY_ACCT_NO
     *
     * @param repayAcctNo the value for SSCF_CHANNEL.REPAY_ACCT_NO
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setRepayAcctNo(String repayAcctNo) {
        this.repayAcctNo = repayAcctNo == null ? null : repayAcctNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.CUST_NO
     *
     * @return the value of SSCF_CHANNEL.CUST_NO
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public String getCustNo() {
        return custNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.CUST_NO
     *
     * @param custNo the value for SSCF_CHANNEL.CUST_NO
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setCustNo(String custNo) {
        this.custNo = custNo == null ? null : custNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.BATCH_FLAG
     *
     * @return the value of SSCF_CHANNEL.BATCH_FLAG
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public String getBatchFlag() {
        return batchFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.BATCH_FLAG
     *
     * @param batchFlag the value for SSCF_CHANNEL.BATCH_FLAG
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setBatchFlag(String batchFlag) {
        this.batchFlag = batchFlag == null ? null : batchFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.BATCH_ACCT
     *
     * @return the value of SSCF_CHANNEL.BATCH_ACCT
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public String getBatchAcct() {
        return batchAcct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.BATCH_ACCT
     *
     * @param batchAcct the value for SSCF_CHANNEL.BATCH_ACCT
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setBatchAcct(String batchAcct) {
        this.batchAcct = batchAcct == null ? null : batchAcct.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column SSCF_CHANNEL.CHANNEL_OWER
     *
     * @return the value of SSCF_CHANNEL.CHANNEL_OWER
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public String getChannelOwer() {
        return channelOwer;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column SSCF_CHANNEL.CHANNEL_OWER
     *
     * @param channelOwer the value for SSCF_CHANNEL.CHANNEL_OWER
     *
     * @mbggenerated Tue Nov 01 16:07:14 CST 2016
     */
    public void setChannelOwer(String channelOwer) {
        this.channelOwer = channelOwer == null ? null : channelOwer.trim();
    }
}